# Chapter 14: problem-solving cases. phases: kind in 진단 / 원인 / 해결 / 확인
H = "~ %"

CASES = [
dict(n=1, title="디스크 공간이 부족하다는 경고가 뜬다",
     symptom="사진을 저장하려는데 \"디스크가 거의 가득 찼습니다\"라는 알림이 뜬다. 무엇이 공간을 차지하는지 Finder로는 도무지 알 수가 없다.",
     phases=[
      dict(kind="진단", title="정말로 얼마나 찼는지 숫자로 확인한다",
           text="먼저 느낌이 아니라 숫자를 본다. macOS는 시스템 파일과 내 데이터를 나눠 담는데, 내 파일이 들어 있는 곳은 /System/Volumes/Data다.",
           lines=[(H, "df -h /System/Volumes/Data", ["Filesystem       Size   Used  Avail Capacity  Mounted on", "/dev/disk3s5    460Gi  438Gi   12Gi    98%    /System/Volumes/Data"])],
           dissect=[("df -h /System/Volumes/Data",
                     [("df", "디스크의 전체·사용·남은 공간을 보여주는 명령 (disk free)"),
                      ("-h", "바이트 숫자 대신 Gi(기가바이트) 같은 읽기 쉬운 단위로"),
                      ("/System/Volumes/Data", "내 문서·사진·앱 데이터가 실제로 저장되는 영역")],
                     "460Gi 중 438Gi를 쓰고 12Gi만 남았다(Avail). Capacity 98%, 경고가 뜰 만하다. 일부 칸은 생략했다.")]),
      dict(kind="원인", title="어느 폴더가 무거운지 좁혀 간다",
           text="홈 폴더를 한 단계씩 내려가며 큰 폴더를 찾는다. 가장 큰 곳으로 들어가 같은 방법을 반복하면 범인에 금방 닿는다.",
           lines=[(H, "du -h -d 1 ~ 2>/dev/null | sort -rh | head -5", ["312G    /Users/jimin", "148G    /Users/jimin/Movies", " 96G    /Users/jimin/Library", " 41G    /Users/jimin/Downloads", " 18G    /Users/jimin/Documents"]),
                  (H, "find ~/Movies ~/Downloads -size +2G", ["/Users/jimin/Movies/강의녹화/0912_1강.mov", "/Users/jimin/Movies/강의녹화/0919_2강.mov", "/Users/jimin/Downloads/ubuntu-24.04.iso"])],
           dissect=[("du -h -d 1 ~ 2>/dev/null | sort -rh | head -5",
                     [("du", "폴더가 차지한 용량을 재는 명령 (disk usage)"),
                      ("-h", "K·M·G 단위로 읽기 쉽게"),
                      ("-d 1", "홈 바로 아래 폴더까지만 나눠서 합계를 낸다 (depth)"),
                      ("~", "내 홈 폴더"),
                      ("2>/dev/null", "\"권한 없음\" 같은 오류 메시지를 버리는 곳(/dev/null)으로 보낸다. 결과만 깔끔하게 보인다"),
                      ("| sort -rh", "단위를 이해하며(-h) 큰 것부터(-r) 정렬"),
                      ("| head -5", "그중 위에서 5줄만")],
                     "첫 줄은 홈 전체의 합계다. 그 아래에서 Movies(148G)가 가장 크다. 범인이 있는 방을 찾았다."),
                    ("find ~/Movies ~/Downloads -size +2G",
                     [("find", "조건에 맞는 파일을 찾는 명령"),
                      ("~/Movies ~/Downloads", "뒤질 폴더 두 곳. 공백으로 나열한다"),
                      ("-size +2G", "2GB보다 큰 파일만")],
                     "강의 녹화 파일들과 예전에 받아 둔 설치 이미지(.iso)가 나왔다. 녹화는 보관해야 하지만 맥 안에 둘 필요는 없고, .iso는 이미 쓸 일이 끝났다.")]),
      dict(kind="해결", title="옮길 것은 옮기고, 버릴 것은 버린다",
           text="녹화 파일은 외장하드로 옮긴다. 이때 바로 지우지 말고 복사 → 똑같은지 확인 → 원본 삭제 순서를 지킨다. 설치 이미지는 휴지통으로 보낸다.",
           lines=[(H, "rsync -av ~/Movies/강의녹화/ /Volumes/Backup/강의녹화/", ["sending incremental file list", "0912_1강.mov", "0919_2강.mov", "sent 96,412,904,221 bytes"]),
                  (H, "diff -rq ~/Movies/강의녹화 /Volumes/Backup/강의녹화", ["(출력 없음)"]),
                  (H, "rm -r ~/Movies/강의녹화", ["(출력 없음)"]),
                  (H, "mv ~/Downloads/ubuntu-24.04.iso ~/.Trash/", ["(출력 없음)"])],
           dissect=[("rsync -av ~/Movies/강의녹화/ /Volumes/Backup/강의녹화/",
                     [("rsync", "복사 도중 끊겨도 이어서 할 수 있는 동기화 명령"),
                      ("-a", "날짜·권한까지 원본 그대로"),
                      ("-v", "복사하는 파일 이름을 보여준다"),
                      ("~/Movies/강의녹화/", "끝의 /는 \"폴더 안의 내용물을\"이라는 뜻"),
                      ("/Volumes/Backup/강의녹화/", "외장하드(이름 Backup) 안의 목적지. 연결한 디스크는 /Volumes 아래에 나타난다")],
                     "약 96GB가 복사됐다. 대용량 복사는 cp보다 rsync가 안전하다. 중간에 끊겨도 같은 명령을 다시 실행하면 남은 것만 복사한다."),
                    ("diff -rq ~/Movies/강의녹화 /Volumes/Backup/강의녹화",
                     [("diff", "두 대상을 비교하는 명령"),
                      ("-r", "폴더 안의 파일까지 모두 비교"),
                      ("-q", "어디가 다른지는 빼고 다른 파일이 있는지만 알려준다")],
                     "아무것도 나오지 않으면 두 폴더가 완전히 같다는 뜻이다. 이 확인을 거쳐야 원본을 지워도 된다."),
                    ("rm -r ~/Movies/강의녹화",
                     [("rm", "휴지통을 거치지 않고 지우는 명령"),
                      ("-r", "폴더와 그 안의 파일까지 모두")],
                     "원본이 사라진다. 되돌릴 수 없으므로 반드시 바로 앞의 diff로 복사본을 확인한 다음에 실행한다."),
                    ("mv ~/Downloads/ubuntu-24.04.iso ~/.Trash/",
                     [("mv", "파일을 옮기는 명령"),
                      ("~/.Trash/", "Finder 휴지통의 실제 위치")],
                     "rm 대신 휴지통으로 보냈으니 필요하면 되살릴 수 있다. 단, 휴지통을 비워야 공간이 실제로 생긴다.")]),
      dict(kind="확인", title="공간이 돌아왔는지 다시 잰다",
           text="Finder에서 휴지통을 비운 뒤, 처음과 같은 명령으로 다시 확인한다. 해결은 같은 측정으로 끝내야 한다.",
           lines=[(H, "df -h /System/Volumes/Data", ["Filesystem       Size   Used  Avail Capacity  Mounted on", "/dev/disk3s5    460Gi  290Gi  160Gi    65%    /System/Volumes/Data"])],
           dissect=[])],
     prevent="다운로드 폴더는 공간 도둑의 단골 은신처다. 한 달에 한 번 find ~/Downloads -mtime +30 으로 30일 넘게 방치된 파일을 확인하고 정리하자.",
     used=["df", "du", "sort", "head", "find", "rsync", "diff", "rm", "mv"]),

dict(n=2, title="맥이 갑자기 느려지고 팬이 요란하게 돈다",
     symptom="아무것도 하지 않는데 팬이 쉬지 않고 돌고, 창 전환도 버벅인다. 무엇이 맥을 괴롭히고 있을까.",
     phases=[
      dict(kind="진단", title="CPU를 가장 많이 쓰는 프로그램을 찾는다",
           text="느려졌다면 거의 항상 누군가 CPU를 독차지하고 있다. 사용량 순으로 줄 세워 맨 위를 본다.",
           lines=[(H, "ps aux -r | head -4", ["USER   PID  %CPU %MEM  ...  COMMAND", "jimin 5123 298.4  3.1  ...  node /Users/jimin/old-project/server.js", "jimin  612  11.8  1.2  ...  WindowServer", "jimin 4410   6.2  4.8  ...  Safari"])],
           dissect=[("ps aux -r | head -4",
                     [("ps", "실행 중인 프로그램 목록을 보여주는 명령 (process status)"),
                      ("aux", "모든 사용자(a), 보기 좋은 형식(u), 뒤에서 도는 것까지(x). 앞에 -를 붙이지 않는 옛 방식이다"),
                      ("-r", "CPU를 많이 쓰는 순서로 정렬 (macOS)"),
                      ("| head -4", "제목 줄과 상위 3개만")],
                     "%CPU가 298.4%인 node가 있다. 100%가 코어 하나를 꽉 채운 상태이니, 코어 세 개를 혼자 쓰고 있다는 뜻이다. PID(고유 번호)는 5123.")]),
      dict(kind="원인", title="그 프로그램이 무엇이고 언제부터 돌았는지 본다",
           text="이름만으로는 부족하다. 언제부터 실행 중인지, 어느 폴더에서 시작됐는지 확인하면 정체가 드러난다.",
           lines=[(H, "ps -p 5123 -o pid,etime,command", ["  PID     ELAPSED COMMAND", " 5123  2-03:14:22 node /Users/jimin/old-project/server.js"])],
           dissect=[("ps -p 5123 -o pid,etime,command",
                     [("-p 5123", "PID 5123번 프로그램만 본다 (process)"),
                      ("-o", "보고 싶은 칸만 골라 출력한다 (output)"),
                      ("pid,etime,command", "번호, 실행된 지 얼마나 됐는지(elapsed time), 실행 명령")],
                     "ELAPSED가 2-03:14:22, 즉 2일 3시간째 돌고 있다. 이틀 전 old-project에서 켜 두고 잊어버린 개발 서버가 무한 반복에 빠진 것이다.")]),
      dict(kind="해결", title="정중하게 끄고, 안 되면 강제로 끈다",
           text="먼저 \"정리하고 끝내 달라\"는 정상 종료를 보낸다. 잠시 뒤에도 살아 있으면 그때 강제 종료한다.",
           lines=[(H, "kill 5123", ["(출력 없음)"]),
                  (H, "ps -p 5123", ["  PID TTY           TIME CMD", " 5123 ??       412:03.11 node /Users/jimin/old-project/server.js"]),
                  (H, "kill -9 5123", ["(출력 없음)"])],
           dissect=[("kill 5123",
                     [("kill", "프로그램에 신호를 보내는 명령"),
                      ("5123", "신호를 받을 PID. 숫자 옵션이 없으니 정상 종료 요청(-15)이 간다")],
                     "조용하지만, 바로 이어서 확인해 보니 아직 살아 있다. 무한 반복에 빠진 프로그램은 부탁을 들을 여유가 없기도 하다."),
                    ("kill -9 5123",
                     [("-9", "SIGKILL. 프로그램이 거부할 수 없는 강제 종료. 저장하지 않은 내용은 사라진다")],
                     "운영체제가 직접 끝낸다. 반드시 정상 종료를 먼저 시도하고, 안 될 때만 쓴다.")]),
      dict(kind="확인", title="다시 줄을 세워 본다",
           text="같은 명령으로 확인한다. 맨 위가 평범한 수치로 돌아왔다면 해결이다. 팬 소리도 곧 잦아든다.",
           lines=[(H, "ps aux -r | head -3", ["USER   PID %CPU %MEM  ...  COMMAND", "jimin  612  9.4  1.2  ...  WindowServer", "jimin 4410  5.1  4.8  ...  Safari"])],
           dissect=[])],
     prevent="개발 서버는 창을 닫기 전에 Control+C로 끄는 습관을 들이자. 실시간으로 지켜보고 싶을 때는 top -o cpu를 켜 두면 된다(q로 종료).",
     used=["ps", "head", "kill", "top"]),

dict(n=3, title="외장하드가 \"사용 중\"이라며 추출되지 않는다",
     symptom="백업을 마치고 외장하드를 빼려는데 \"'Backup' 디스크가 사용 중이므로 추출할 수 없습니다\"라는 창이 뜬다. 열어 둔 창은 다 닫은 것 같은데.",
     phases=[
      dict(kind="진단", title="누가 그 디스크를 붙잡고 있는지 묻는다",
           text="\"사용 중\"이란 어떤 프로그램이 그 디스크 안의 파일이나 폴더를 열고 있다는 뜻이다. 열린 파일 목록에서 디스크 경로로 거른다.",
           lines=[(H, "lsof +D /Volumes/Backup", ["COMMAND   PID   USER   FD  TYPE  NAME", "Preview  7310  jimin   12r  REG   /Volumes/Backup/2026 결산.pdf", "zsh      7422  jimin  cwd  DIR   /Volumes/Backup"])],
           dissect=[("lsof +D /Volumes/Backup",
                     [("lsof", "어떤 프로그램이 무엇을 열고 있는지 보여주는 명령 (list open files)"),
                      ("+D", "지정한 폴더와 그 아래 전체에서 열린 것을 찾는다 (Directory)"),
                      ("/Volumes/Backup", "외장하드가 연결된 위치")],
                     "범인이 둘이다. 미리보기(Preview)가 PDF를 열고 있고, zsh 한 줄의 FD 칸에 cwd(current working directory)가 보인다. 다른 터미널 창이 cd로 그 디스크 안에 들어가 있는 것이다.")]),
      dict(kind="원인", title="의외의 범인은 나 자신",
           text="Finder 창은 다 닫았지만 미리보기로 결산 PDF를 열어 둔 채였고, 백업하던 터미널 창도 아직 /Volumes/Backup 안에 서 있었다. 폴더 안에 서 있는 것만으로도 \"사용 중\"이 된다.",
           lines=[], dissect=[]),
      dict(kind="해결", title="붙잡은 손을 하나씩 놓게 한다",
           text="미리보기는 앱을 종료하고, 디스크 안에 서 있던 터미널 창은 홈으로 나온다.",
           lines=[(H, "killall Preview", ["(출력 없음)"]),
                  ("Backup %", "cd ~", ["→ 프롬프트가 ~ % 로 바뀜 (그 창에서 실행)"])],
           dissect=[("killall Preview",
                     [("killall", "이름이 같은 프로그램을 모두 종료하는 명령. kill의 형제"),
                      ("Preview", "미리보기 앱의 실제 프로그램 이름")],
                     "미리보기가 닫힌다. 저장할 게 있다면 앱에서 직접 닫는 편이 더 안전하다."),
                    ("cd ~",
                     [("cd", "폴더 이동"),
                      ("~", "홈 폴더")],
                     "그 터미널 창이 디스크 밖으로 나왔다.")]),
      dict(kind="확인", title="아무도 붙잡고 있지 않은지 확인하고 추출한다",
           text="같은 lsof를 다시 실행해 아무것도 나오지 않으면 안전하다. 추출은 Finder에서 해도 되고 터미널에서 해도 된다.",
           lines=[(H, "lsof +D /Volumes/Backup", ["(출력 없음)"]),
                  (H, "diskutil eject /Volumes/Backup", ["Disk /Volumes/Backup ejected"])],
           dissect=[],
           outside=[("diskutil eject", "diskutil은 디스크를 관리하는 macOS 도구다. eject는 Finder의 추출 버튼과 같은 일을 한다.")])],
     prevent="외장하드 작업을 끝낸 터미널 창은 cd ~ 로 빠져나오는 습관을 들이자. 추출이 안 될 때는 lsof +D 하나면 이유를 알 수 있다.",
     used=["lsof", "kill", "cd"]),

dict(n=4, title="스크립트를 실행하면 Permission denied가 뜬다",
     symptom="동료가 준 배포 스크립트를 실행했더니 \"permission denied\"만 뜨고 아무 일도 일어나지 않는다. 설정 파일을 고치려 해도 같은 말이 나온다.",
     phases=[
      dict(kind="진단", title="오류를 그대로 다시 보고, 권한을 확인한다",
           text="permission denied는 \"허락되지 않았다\"는 뜻이다. 누구에게 무엇이 허락되지 않았는지 ls -l로 확인한다.",
           lines=[(H, "./deploy.sh", ["zsh: permission denied: ./deploy.sh"]),
                  (H, "ls -l deploy.sh", ["-rw-r--r--  1 jimin  staff  420  9 30 10:12 deploy.sh"])],
           dissect=[("./deploy.sh",
                     [("./", "\"지금 폴더에 있는\"이라는 뜻. 스크립트는 이렇게 경로를 붙여 실행한다"),
                      ("deploy.sh", "실행하려는 스크립트 파일")],
                     "셸이 실행 자체를 거부했다."),
                    ("ls -l deploy.sh",
                     [("-l", "권한·주인·크기·날짜까지 자세히")],
                     "맨 앞 -rw-r--r--를 세 칸씩 끊어 읽는다. 주인(rw-)·그룹(r--)·그 외(r--). 어디에도 실행 권한 x가 없다. 파일을 메신저로 주고받으면서 실행 권한이 빠진 것이다.")]),
      dict(kind="해결", title="실행 권한을 더한다",
           text="파일에 x(실행) 권한을 붙여 주면 된다. 붙였는지 다시 확인하고 실행한다.",
           lines=[(H, "chmod +x deploy.sh", ["(출력 없음)"]),
                  (H, "ls -l deploy.sh", ["-rwxr-xr-x  1 jimin  staff  420  9 30 10:12 deploy.sh"]),
                  (H, "./deploy.sh", ["배포를 시작합니다...", "완료!"])],
           dissect=[("chmod +x deploy.sh",
                     [("chmod", "권한을 바꾸는 명령 (change mode)"),
                      ("+x", "실행(x) 권한을 더한다(+). 누구에게인지 안 적으면 모두에게")],
                     "rw-가 rwx로 바뀌었다. 이제 실행된다.")]),
      dict(kind="원인", title="두 번째 증상: 이번엔 파일 주인이 다르다",
           text="이어서 설정 파일에 한 줄을 덧붙이려는데 또 거부당한다. 이번에는 권한이 아니라 주인이 문제다.",
           lines=[(H, 'echo "PORT=8080" >> config.env', ["zsh: permission denied: config.env"]),
                  (H, "ls -l config.env", ["-rw-r--r--  1 root  staff  88  9 29 17:40 config.env"])],
           dissect=[("ls -l config.env",
                     [("root", "세 번째 칸이 파일의 주인. root는 관리자 계정이다")],
                     "주인이 jimin이 아니라 root다. 어제 sudo를 붙여 이 파일을 만든 탓이다. 주인(root)만 쓸 수 있고(rw-), 나는 그 외(r--)라 읽기만 된다.")]),
      dict(kind="해결", title="주인을 나로 되돌린다",
           text="남의 파일 주인을 바꾸는 일이라 관리자 권한(sudo)이 필요하다. 한 번만 빌려서 주인을 나로 바꾼다.",
           lines=[(H, "sudo chown $(whoami) config.env", ["Password:"]),
                  (H, "ls -l config.env", ["-rw-r--r--  1 jimin  staff  88  9 29 17:40 config.env"]),
                  (H, 'echo "PORT=8080" >> config.env', ["(출력 없음)"])],
           dissect=[("sudo chown $(whoami) config.env",
                     [("sudo", "이 명령 하나만 관리자 권한으로 실행. 맥 로그인 비밀번호를 묻는다(입력해도 안 보이는 게 정상)"),
                      ("chown", "파일 주인을 바꾸는 명령 (change owner)"),
                      ("$(whoami)", "whoami의 결과, 즉 내 사용자 이름(jimin)이 이 자리에 들어간다"),
                      ("config.env", "주인을 바꿀 파일")],
                     "주인이 jimin으로 바뀌었고, 이제 sudo 없이도 자유롭게 고칠 수 있다.")])],
     prevent="sudo는 꼭 필요할 때만 쓰자. sudo로 만든 파일은 주인이 root가 되어 나중에 이런 문제를 만든다. Permission denied가 뜨면 고민하기 전에 ls -l부터.",
     used=["ls", "chmod", "echo", "sudo", "chown"]),

dict(n=5, title="분명 설치했는데 command not found가 뜬다",
     symptom="Homebrew를 설치하고 안내대로 brew를 입력했더니 \"command not found: brew\". 설치가 실패한 걸까?",
     phases=[
      dict(kind="진단", title="프로그램이 정말 없는지, 못 찾는 것인지 가린다",
           text="셸이 모른다고 해서 파일이 없는 것은 아니다. 셸이 찾는 곳에 없을 뿐일 수 있다. 먼저 which로 셸의 입장을 듣고, ls로 실제 파일이 있는지 직접 본다.",
           lines=[(H, "brew --version", ["zsh: command not found: brew"]),
                  (H, "which brew", ["brew not found"]),
                  (H, "ls /opt/homebrew/bin/brew", ["/opt/homebrew/bin/brew"])],
           dissect=[("which brew",
                     [("which", "명령어가 실제로 어디 있는 프로그램인지 찾는 명령")],
                     "셸이 brew를 찾지 못한다."),
                    ("ls /opt/homebrew/bin/brew",
                     [("/opt/homebrew/bin", "Apple 칩 맥에서 Homebrew가 프로그램을 설치하는 폴더")],
                     "그런데 파일은 분명히 있다. 설치는 성공했고, 셸이 이 폴더를 뒤져 보지 않는 것이 문제다.")]),
      dict(kind="원인", title="셸이 프로그램을 찾는 경로 목록을 본다",
           text="셸은 PATH라는 환경변수에 적힌 폴더들만 차례로 뒤져 명령을 찾는다. 그 목록을 출력해 본다.",
           lines=[(H, "echo $PATH", ["/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"])],
           dissect=[("echo $PATH",
                     [("echo", "받은 글자를 그대로 출력"),
                      ("$PATH", "PATH 변수의 값. $를 붙이면 변수 이름 대신 그 안의 내용이 들어간다")],
                     "콜론(:)으로 구분된 폴더 다섯 곳 어디에도 /opt/homebrew/bin이 없다. 원인을 찾았다.")]),
      dict(kind="해결", title="PATH에 폴더를 추가하고, 설정 파일에도 적어 둔다",
           text="지금 창에 바로 추가해 되는지 확인한 뒤, 터미널을 새로 열어도 유지되도록 ~/.zshrc에 기록하고 적용한다.",
           lines=[(H, 'export PATH="/opt/homebrew/bin:$PATH"', ["(출력 없음)"]),
                  (H, "echo 'export PATH=\"/opt/homebrew/bin:$PATH\"' >> ~/.zshrc", ["(출력 없음)"]),
                  (H, "source ~/.zshrc", ["(출력 없음)"])],
           dissect=[('export PATH="/opt/homebrew/bin:$PATH"',
                     [("export", "변수를 설정하고, 이 셸에서 실행하는 모든 프로그램에도 전달"),
                      ("/opt/homebrew/bin:", "새로 추가할 폴더. 앞에 둘수록 먼저 찾는다"),
                      ("$PATH", "원래 목록을 그 뒤에 그대로 이어 붙인다. 이걸 빠뜨리면 기존 명령이 모두 사라진다")],
                     "지금 이 창에서는 brew가 된다. 하지만 창을 닫으면 사라진다."),
                    ("echo '…' >> ~/.zshrc",
                     [("작은따옴표 '…'", "안의 $PATH가 지금 바로 풀리지 않고 글자 그대로 파일에 적히게 한다"),
                      (">> ~/.zshrc", "터미널이 켜질 때마다 읽는 설정 파일 끝에 덧붙인다")],
                     "이제 새 창에서도 자동으로 PATH가 설정된다. source로 지금 창에도 바로 반영했다.")]),
      dict(kind="확인", title="셸이 이제 찾는지 묻는다",
           text="처음 실패했던 명령을 그대로 다시 실행한다.",
           lines=[(H, "which brew", ["/opt/homebrew/bin/brew"]),
                  (H, "brew --version", ["Homebrew 4.4.0"])],
           dissect=[],
           outside=[("brew", "Homebrew는 맥용 프로그램 설치 도구다. Homebrew는 설치를 마칠 때 PATH 설정 명령을 화면에 안내해 주는데, 이 안내를 건너뛰면 지금 같은 일이 생긴다.")])],
     prevent="command not found를 만나면 which → ls → echo $PATH 순서로 확인하자. \"없는 것\"과 \"못 찾는 것\"을 구별하면 대부분 5분 안에 해결된다.",
     used=["which", "ls", "echo", "export", "source"]),

dict(n=6, title="어제 받은 파일이 어디 있는지 모르겠다",
     symptom="어제 메일로 받은 강의 계약서를 어딘가에 저장했는데 파일 이름도, 폴더도 기억나지 않는다. 기억나는 건 \"계약\"이라는 단어가 들어 있다는 것뿐.",
     phases=[
      dict(kind="진단", title="가장 흔한 곳부터 최근 순으로 본다",
           text="대부분은 다운로드 폴더에 있다. 최근에 생긴 파일부터 몇 개만 본다.",
           lines=[(H, "ls -lt ~/Downloads | head -4", ["total 18244", "-rw-r--r--  1 jimin  staff  2381022  9 30 09:02 IMG_2231.HEIC", "-rw-r--r--  1 jimin  staff   120412  9 29 21:40 영수증.pdf", "-rw-r--r--  1 jimin  staff  5501123  9 29 18:11 강의자료_v3.key"])],
           dissect=[("ls -lt ~/Downloads | head -4",
                     [("-l", "자세히"),
                      ("-t", "최근에 수정된 순서로 (time)"),
                      ("| head -4", "위에서 네 줄만. 첫 줄 total은 합계라 실제 파일은 세 개")],
                     "계약서처럼 보이는 파일은 없다. 다른 곳에 저장했나 보다.")]),
      dict(kind="원인", title="날짜와 내용으로 범위를 좁힌다",
           text="\"어제 이후 생긴 PDF\"로 찾아보고, 그래도 모르면 파일 이름이 아니라 내용으로 찾는다. Spotlight의 색인을 쓰면 문서 속 글자까지 순식간에 뒤진다.",
           lines=[(H, 'find ~/Documents ~/Desktop -mtime -1 -name "*.pdf"', ["/Users/jimin/Desktop/스캔_0929.pdf"]),
                  (H, 'mdfind -onlyin ~ "위탁 계약"', ["/Users/jimin/Documents/업무/2026-수탁-최종.pdf"])],
           dissect=[('find ~/Documents ~/Desktop -mtime -1 -name "*.pdf"',
                     [("-mtime -1", "하루 안에 수정된 것 (modification time)"),
                      ('-name "*.pdf"', "이름이 .pdf로 끝나는 것")],
                     "스캔 파일 하나뿐이다. 이름에 계약이라는 단어가 없어 이름으로는 찾기 어렵다."),
                    ('mdfind -onlyin ~ "위탁 계약"',
                     [("mdfind", "Spotlight가 만들어 둔 색인에서 찾는 macOS 전용 명령"),
                      ("-onlyin ~", "홈 폴더 안에서만"),
                      ('"위탁 계약"', "파일 이름뿐 아니라 문서 안의 글자까지 찾는다")],
                     "파일 이름은 \"2026-수탁-최종.pdf\"였다. 이름에는 계약이 없었지만 본문에 있는 글자로 찾아냈다.")]),
      dict(kind="해결", title="Finder에서 바로 보여주고 연다",
           text="찾은 경로를 그대로 이용한다. 경로에 공백이나 한글이 있으면 따옴표로 감싼다.",
           lines=[(H, 'open -R "/Users/jimin/Documents/업무/2026-수탁-최종.pdf"', ["→ Finder에서 파일이 선택된 채로 폴더가 열림"]),
                  (H, 'open "/Users/jimin/Documents/업무/2026-수탁-최종.pdf"', ["→ 미리보기로 계약서가 열림"])],
           dissect=[('open -R "…"',
                     [("open", "Finder에서 더블클릭한 것처럼 여는 macOS 전용 명령"),
                      ("-R", "열지 않고 위치만 보여준다 (Reveal)")],
                     "파일이 어느 폴더에 있는지 눈으로 확인하고, 필요하면 원하는 곳으로 옮긴다.")])],
     prevent="파일 이름이 기억나지 않으면 find보다 mdfind가 빠르다. 내용 속 단어 하나만 기억해도 찾을 수 있다.",
     used=["ls", "head", "find", "mdfind", "open"]),

dict(n=7, title="인터넷이 안 된다. 어디가 문제일까",
     symptom="브라우저에서 사이트가 열리지 않는다. 와이파이 아이콘은 멀쩡해 보인다. 공유기 문제일까, 인터넷 회사 문제일까, 내 맥 문제일까.",
     phases=[
      dict(kind="진단", title="가까운 곳부터 한 칸씩 멀리 신호를 보낸다",
           text="집 공유기 → 인터넷 너머의 서버(숫자 주소) → 이름 주소 순서로 확인한다. 어디서 끊기는지가 곧 원인의 위치다.",
           lines=[(H, "ping -c 3 192.168.0.1", ["3 packets transmitted, 3 packets received, 0.0% packet loss"]),
                  (H, "ping -c 3 8.8.8.8", ["3 packets transmitted, 3 packets received, 0.0% packet loss"]),
                  (H, "ping -c 3 google.com", ["ping: cannot resolve google.com: Unknown host"])],
           dissect=[("ping -c 3 192.168.0.1",
                     [("ping", "상대에게 신호를 보내 응답이 오는지 확인하는 명령"),
                      ("-c 3", "세 번만 보내고 멈춘다 (count)"),
                      ("192.168.0.1", "흔히 쓰는 집 공유기 주소")],
                     "공유기까지는 잘 연결된다."),
                    ("ping -c 3 8.8.8.8",
                     [("8.8.8.8", "구글이 운영하는 공개 서버의 숫자 주소. 인터넷 너머까지 가는지 볼 때 쓴다")],
                     "인터넷 너머까지도 신호가 오간다. 인터넷 선 자체는 멀쩡하다."),
                    ("ping -c 3 google.com",
                     [("google.com", "이번엔 숫자가 아니라 이름 주소")],
                     "cannot resolve, 이름을 숫자 주소로 바꾸지 못했다. 숫자로는 되는데 이름으로는 안 된다.")]),
      dict(kind="원인", title="이름을 숫자로 바꿔 주는 DNS가 문제다",
           text="인터넷의 주소록 역할을 하는 DNS가 응답하지 않거나, 맥이 기억해 둔 주소록(캐시)이 꼬인 상태다. 연결은 멀쩡하니 공유기를 껐다 켜기 전에 맥의 주소록부터 비워 본다.",
           lines=[], dissect=[]),
      dict(kind="해결", title="맥의 DNS 기억을 비운다",
           text="관리자 권한이 필요한 두 명령을 세미콜론(;)으로 이어 한 번에 실행한다.",
           lines=[(H, "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder", ["Password:"])],
           dissect=[("sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder",
                     [("sudo", "관리자 권한으로 실행"),
                      ("dscacheutil -flushcache", "맥이 기억해 둔 이름-주소 목록을 비운다 (macOS 도구)"),
                      (";", "앞 명령이 끝나면 이어서 다음 명령을 실행"),
                      ("killall -HUP", "HUP 신호를 보낸다. 끄라는 뜻이 아니라 \"설정을 다시 읽으라\"는 뜻"),
                      ("mDNSResponder", "macOS에서 DNS를 담당하는 프로그램")],
                     "비밀번호를 입력하면 조용히 끝난다. DNS 담당 프로그램이 주소록을 새로 채우기 시작한다.")]),
      dict(kind="확인", title="이름으로 다시 신호를 보내고, 사이트에 직접 물어본다",
           text="실패했던 명령을 다시 실행하고, 웹 서버가 정상 응답하는지까지 확인한다.",
           lines=[(H, "ping -c 3 google.com", ["64 bytes from 142.250.206.46: icmp_seq=0 ttl=117 time=31.2 ms", "3 packets transmitted, 3 packets received, 0.0% packet loss"]),
                  (H, "curl -I https://www.google.com", ["HTTP/2 200", "content-type: text/html; charset=ISO-8859-1"])],
           dissect=[("curl -I https://www.google.com",
                     [("curl", "인터넷 주소와 데이터를 주고받는 명령"),
                      ("-I", "내용은 빼고 서버의 응답 정보만")],
                     "HTTP/2 200은 \"정상\"이라는 뜻이다. 브라우저도 다시 열릴 것이다.")])],
     prevent="인터넷 문제는 가까운 곳부터 멀리 ping을 보내 보면 대부분 위치가 드러난다. 공유기 → 8.8.8.8 → 이름 주소, 이 세 줄을 기억해 두자.",
     used=["ping", "sudo", "kill", "curl"]),

dict(n=8, title="문서 수십 개에 같은 오타가 있다",
     symptom="강의 자료를 다 만들고 보니 \"쿠버네티스\"를 모든 문서에 \"쿠버네티즈\"로 잘못 썼다. 파일이 수십 개라 하나씩 열어 고치기엔 막막하다.",
     phases=[
      dict(kind="진단", title="오타가 몇 개 파일에 퍼져 있는지 센다",
           text="고치기 전에 범위부터 안다. 오타가 들어 있는 파일 이름을 뽑아 개수를 세고, 실제로 어떻게 쓰였는지 몇 줄 본다.",
           lines=[(H, 'grep -rl "쿠버네티즈" docs/ | wc -l', ["      37"]),
                  (H, 'grep -rn "쿠버네티즈" docs/ | head -3', ["docs/03-intro.md:12:쿠버네티즈는 컨테이너를 관리하는 도구다.", "docs/03-intro.md:40:쿠버네티즈 클러스터를 만든다.", "docs/05-deploy.md:7:쿠버네티즈에 배포하기"])],
           dissect=[('grep -rl "쿠버네티즈" docs/ | wc -l',
                     [("grep -r", "docs 폴더 아래 모든 파일에서 찾는다"),
                      ("-l", "내용은 빼고 파일 이름만"),
                      ("| wc -l", "파일 이름 줄 수 = 파일 개수")],
                     "37개 파일에 오타가 있다. 손으로 고치면 한나절 일이다."),
                    ('grep -rn "쿠버네티즈" docs/ | head -3',
                     [("-n", "줄 번호를 붙인다"),
                      ("| head -3", "세 줄만 맛보기")],
                     "단어 전체를 바꿔도 다른 말이 망가지지 않는지 실제 문장을 보고 판단한다.")]),
      dict(kind="해결", title="찾은 파일들에만 한꺼번에 바꾸기를 적용한다",
           text="grep이 찾은 파일 목록을 xargs로 sed에 넘긴다. 원본은 .bak 파일로 남겨 두어 문제가 생기면 되돌릴 수 있게 한다.",
           lines=[(H, "grep -rl \"쿠버네티즈\" docs/ | xargs sed -i .bak 's/쿠버네티즈/쿠버네티스/g'", ["(출력 없음)"])],
           dissect=[("grep -rl \"쿠버네티즈\" docs/ | xargs sed -i .bak 's/쿠버네티즈/쿠버네티스/g'",
                     [("grep -rl … docs/", "오타가 있는 파일 이름 목록을 만든다"),
                      ("| xargs", "그 목록을 뒤 명령의 인자(재료)로 바꿔 붙인다. sed는 파이프로 받은 글자를 파일 이름으로 여기지 않기 때문에 필요하다"),
                      ("sed", "글자를 바꾸는 명령 (stream editor)"),
                      ("-i .bak", "원본 파일을 직접 고치되, 고치기 전 내용을 같은 이름.bak으로 남긴다"),
                      ("'s/쿠버네티즈/쿠버네티스/g'", "바꾸기(s) 규칙. 한 줄에 여러 번 있어도 모두(g)")],
                     "37개 파일이 한 번에 고쳐졌다. 각 파일 옆에 원래 내용이 담긴 .bak 파일이 생겼다.")]),
      dict(kind="확인", title="남은 오타가 없는지, 바뀐 곳이 맞는지 본다",
           text="같은 grep으로 오타가 0개인지 확인하고, 파일 하나를 골라 원본(.bak)과 비교해 의도한 곳만 바뀌었는지 눈으로 본다. 문제없으면 백업을 지운다.",
           lines=[(H, 'grep -rl "쿠버네티즈" docs/ --exclude="*.bak" | wc -l', ["       0"]),
                  (H, "diff docs/03-intro.md.bak docs/03-intro.md", ["12c12", "< 쿠버네티즈는 컨테이너를 관리하는 도구다.", "---", "> 쿠버네티스는 컨테이너를 관리하는 도구다."]),
                  (H, 'find docs -name "*.bak" -delete', ["(출력 없음)"])],
           dissect=[('grep -rl "쿠버네티즈" docs/ --exclude="*.bak" | wc -l',
                     [('--exclude="*.bak"', "백업 파일에는 옛 글자가 그대로 있으니 검사에서 뺀다")],
                     "0개. 오타가 모두 사라졌다."),
                    ("diff docs/03-intro.md.bak docs/03-intro.md",
                     [("diff", "두 파일을 비교"),
                      ("12c12", "원본 12번째 줄이 새 파일 12번째 줄로 바뀌었다(c = change)"),
                      ("< 와 >", "<는 원본(왼쪽)에만 있던 줄, >는 새 파일(오른쪽)에만 있는 줄")],
                     "의도한 단어만 바뀌었다. 확인이 끝났으니 find -delete로 .bak 파일을 정리한다.")])],
     prevent="여러 파일을 한꺼번에 고칠 때는 grep으로 범위 확인 → sed -i .bak로 백업 남기며 수정 → grep과 diff로 확인 → 백업 삭제. 이 네 박자를 지키면 무서울 게 없다. 파일 이름에 공백이 있을 수 있다면 grep -rl --null … | xargs -0 을 쓴다.",
     used=["grep", "wc", "head", "xargs", "sed", "diff", "find"]),
]
