# (flag, origin_html, meaning) — <b> marks the letter the flag comes from
OPTIONS = {
    "mkdir": [("-p", "<b>p</b>arents", "상위 폴더가 없어도 한 번에 생성"),
              ("-m", "<b>m</b>ode", "생성과 동시에 권한 지정"),
              ("-v", "<b>v</b>erbose", "만든 폴더 이름을 하나하나 출력")],
    "rm": [("-r", "<b>r</b>ecursive", "폴더 안쪽까지 재귀적으로 삭제"),
           ("-f", "<b>f</b>orce", "확인 없이 강제 삭제"),
           ("-i", "<b>i</b>nteractive", "지우기 전에 하나씩 물어봄"),
           ("-v", "<b>v</b>erbose", "지운 파일 이름 출력")],
    "cp": [("-R", "<b>R</b>ecursive", "폴더 통째로 복사 (-r도 동작)"),
           ("-i", "<b>i</b>nteractive", "덮어쓰기 전에 물어봄"),
           ("-n", "<b>n</b>o-clobber", "이미 있으면 덮어쓰지 않음"),
           ("-v", "<b>v</b>erbose", "복사 과정 출력"),
           ("-p", "<b>p</b>reserve", "권한·수정 시각 그대로 유지")],
    "mv": [("-i", "<b>i</b>nteractive", "덮어쓰기 전에 물어봄"),
           ("-n", "<b>n</b>o-clobber", "이미 있으면 덮어쓰지 않음"),
           ("-f", "<b>f</b>orce", "묻지 않고 덮어씀"),
           ("-v", "<b>v</b>erbose", "이동 과정 출력")],
    "ls": [("-l", "<b>l</b>ong", "권한·크기·날짜까지 긴 형식으로"),
           ("-a", "<b>a</b>ll", "숨김 파일까지 전부"),
           ("-h", "<b>h</b>uman-readable", "크기를 K·M·G 단위로"),
           ("-t", "<b>t</b>ime", "수정 시각 순 정렬"),
           ("-S", "<b>S</b>ize", "크기 순 정렬"),
           ("-r", "<b>r</b>everse", "정렬 순서 뒤집기"),
           ("-R", "<b>R</b>ecursive", "하위 폴더까지 모두")],
    "find": [("-name", "<b>name</b>", "이름으로 찾기 (대소문자 구분)"),
             ("-iname", "<b>i</b>nsensitive name", "대소문자 무시하고 이름으로"),
             ("-type", "<b>type</b> (f=<b>f</b>ile, d=<b>d</b>irectory)", "파일 또는 폴더만"),
             ("-size", "<b>size</b>", "크기 조건 (+500M = 500MB 초과)"),
             ("-mtime", "<b>m</b>odification <b>time</b>", "며칠 안에 수정됐는지"),
             ("-exec", "<b>exec</b>ute", "찾은 파일마다 명령 실행")],
    "grep": [("-r", "<b>r</b>ecursive", "하위 폴더까지 검색"),
             ("-i", "<b>i</b>gnore case", "대소문자 무시"),
             ("-n", "line <b>n</b>umber", "줄 번호 표시"),
             ("-v", "in<b>v</b>ert match", "일치하지 않는 줄만"),
             ("-l", "<b>l</b>ist files", "일치한 파일 이름만"),
             ("-c", "<b>c</b>ount", "일치한 줄 개수만"),
             ("-w", "<b>w</b>ord", "단어 단위로만 일치"),
             ("-C", "<b>C</b>ontext", "앞뒤 줄까지 함께 표시"),
             ("-E", "<b>E</b>xtended regex", "확장 정규식 (a|b 같은 표현)")],
    "chmod": [("u / g / o / a", "<b>u</b>ser · <b>g</b>roup · <b>o</b>thers · <b>a</b>ll", "소유자 · 그룹 · 그 외 · 전체"),
              ("r / w / x", "<b>r</b>ead · <b>w</b>rite · e<b>x</b>ecute", "읽기 · 쓰기 · 실행"),
              ("+ / - / =", "add · remove · set", "권한 추가 · 제거 · 정확히 지정"),
              ("-R", "<b>R</b>ecursive", "폴더 안쪽 전체에 적용")],
    "tar": [("-c", "<b>c</b>reate", "새 압축 파일 만들기"),
            ("-x", "e<b>x</b>tract", "압축 풀기"),
            ("-t", "<b>t</b>able of contents", "내용물 목록만 보기"),
            ("-z", "g<b>z</b>ip", "gzip으로 압축·해제 (.tar.gz)"),
            ("-v", "<b>v</b>erbose", "처리 중인 파일 출력"),
            ("-f", "<b>f</b>ile", "대상 파일 이름 지정 (항상 맨 뒤)"),
            ("-C", "<b>C</b>hange directory", "지정한 폴더에서 풀기")],
    "curl": [("-o", "<b>o</b>utput", "지정한 이름으로 저장"),
             ("-O", "remote-name <b>O</b>utput", "서버의 파일 이름 그대로 저장"),
             ("-L", "<b>L</b>ocation", "이동(리다이렉트) 주소를 따라감"),
             ("-I", "head (<b>I</b>nfo)", "본문 없이 헤더 정보만"),
             ("-s", "<b>s</b>ilent", "진행 표시 숨기기"),
             ("-X", "request (관례상 X)", "GET·POST 같은 요청 방식 지정"),
             ("-H", "<b>H</b>eader", "요청 헤더 추가"),
             ("-d", "<b>d</b>ata", "보낼 본문 데이터")],
    "wget": [("-O", "<b>O</b>utput document", "저장할 파일 이름 지정"),
             ("-c", "<b>c</b>ontinue", "끊긴 다운로드 이어받기"),
             ("-i", "<b>i</b>nput file", "주소 목록 파일로 여러 개 받기"),
             ("-r", "<b>r</b>ecursive", "링크를 따라 사이트째 받기")],
    "ssh": [("-p", "<b>p</b>ort", "접속 포트 지정 (기본 22)"),
            ("-i", "<b>i</b>dentity file", "사용할 개인키 파일"),
            ("-v", "<b>v</b>erbose", "연결 과정을 자세히 (문제 진단용)"),
            ("-L", "<b>L</b>ocal forward", "서버 포트를 내 컴퓨터로 연결")],
    "scp": [("-r", "<b>r</b>ecursive", "폴더째 복사"),
            ("-P", "<b>P</b>ort", "포트 지정 (소문자 -p는 preserve가 이미 차지)"),
            ("-p", "<b>p</b>reserve", "수정 시각·권한 유지"),
            ("-i", "<b>i</b>dentity file", "사용할 개인키 파일")],
    "rsync": [("-a", "<b>a</b>rchive", "권한·시각 유지하며 폴더째 복사"),
              ("-v", "<b>v</b>erbose", "전송 파일 목록 출력"),
              ("-z", "<b>z</b>ip (compress)", "전송 중 압축"),
              ("-P", "<b>P</b>artial + <b>P</b>rogress", "진행률 표시, 끊기면 이어받기"),
              ("-n", "<b>n</b>o action (dry-run)", "실제로는 하지 않고 미리보기"),
              ("--delete", "delete", "원본에 없는 파일은 대상에서도 삭제"),
              ("--exclude", "exclude", "특정 파일·폴더 제외")],
    "ps": [("a", "<b>a</b>ll users", "다른 사용자의 프로세스까지"),
           ("u", "<b>u</b>ser format", "CPU·메모리 등 사람이 보기 좋은 형식"),
           ("x", "e<b>x</b>tended", "터미널 없이 도는 프로세스까지"),
           ("-r", "<b>r</b>esource (CPU)", "CPU 사용량 순 정렬 (macOS)"),
           ("-m", "<b>m</b>emory", "메모리 사용량 순 정렬 (macOS)")],
    "kill": [("-15", "SIG<b>TERM</b> · terminate", "정상 종료 요청 (기본값)"),
             ("-2", "SIG<b>INT</b> · interrupt", "중단 요청, Ctrl+C와 같음"),
             ("-9", "SIG<b>KILL</b> · kill", "무조건 강제 종료"),
             ("-1", "SIG<b>HUP</b> · hang up", "설정 다시 읽기에 주로 쓰임"),
             ("-l", "<b>l</b>ist", "보낼 수 있는 신호 목록")],
    "diff": [("-u", "<b>u</b>nified", "앞뒤 문맥을 합쳐 보여주는 형식"),
             ("-y", "side-b<b>y</b>-side", "두 파일을 좌우로 나란히"),
             ("-r", "<b>r</b>ecursive", "폴더 전체 비교"),
             ("-q", "<b>q</b>uiet (brief)", "다른지 여부만"),
             ("-w", "ignore all <b>w</b>hitespace", "공백 차이 무시"),
             ("-i", "<b>i</b>gnore case", "대소문자 무시")],
    "du": [("-s", "<b>s</b>ummarize", "합계만 표시"),
           ("-h", "<b>h</b>uman-readable", "K·M·G 단위로"),
           ("-d", "<b>d</b>epth", "몇 단계 하위 폴더까지 볼지"),
           ("-a", "<b>a</b>ll", "파일 하나하나까지")],
    "df": [("-h", "<b>h</b>uman-readable", "1024 기준 K·M·G 단위"),
           ("-H", "<b>H</b>uman (SI)", "1000 기준, Finder와 같은 숫자"),
           ("Avail", "<b>avail</b>able", "남은 공간"),
           ("Use%", "<b>use</b> percent", "사용률")],
}
OPTION_LABELS = {"주요 옵션", "옵션 뜻", "기호 방식", "알아야 할 신호", "주요 컬럼"}

ONELINER = {
    "mkdir": "새 폴더를 만든다.", "rmdir": "빈 폴더만 지운다.", "rm": "파일과 폴더를 휴지통 없이 지운다.",
    "cp": "복사본을 만든다. 원본은 그대로.", "mv": "옮기거나 이름을 바꾼다. 원본은 사라진다.",
    "ls": "폴더 안에 뭐가 있는지 보여준다.", "find": "조건에 맞는 파일을 찾아낸다.",
    "grep": "파일 속 글자를 찾아낸다.", "chmod": "누가 읽고 쓰고 실행할지 정한다.",
    "tar": "여러 파일을 하나로 묶고 푼다.", "curl": "인터넷 주소와 데이터를 주고받는다.",
    "wget": "인터넷에서 파일을 내려받는다.", "ssh": "다른 컴퓨터에 안전하게 접속한다.",
    "scp": "다른 컴퓨터와 파일을 주고받는다.", "rsync": "바뀐 부분만 골라 동기화한다.",
    "ps": "지금 돌고 있는 프로그램을 보여준다.", "kill": "프로그램에 신호를 보내 멈추게 한다.",
    "diff": "두 파일의 다른 곳을 짚어준다.", "du": "폴더가 차지한 용량을 잰다.",
    "df": "디스크에 남은 공간을 잰다.", "alias": "긴 명령에 짧은 별명을 붙인다.",
    "export": "환경변수를 다른 프로그램에도 넘겨준다.", "source": "설정 파일을 지금 창에 바로 적용한다.",
}

# (situation, command, result)
EXAMPLES = {
    "mkdir": [
        ("폴더 여러 개를 한 번에", "mkdir css js images", "세 폴더가 동시에 생긴다. 이름을 공백으로 나열하면 된다."),
        ("프로젝트 뼈대를 한 줄로", "mkdir -p project/{src,docs,tests}", "중괄호 안의 이름마다 폴더가 생긴다. project/src, project/docs, project/tests."),
        ("오늘 날짜로 백업 폴더", "mkdir -p backup/$(date +%Y-%m-%d)", "backup/2026-09-30 생성. $( )는 안쪽 명령의 결과를 그 자리에 끼워 넣는다."),
        ("이름에 띄어쓰기가 있을 때", 'mkdir "강의 자료"', "따옴표가 없으면 '강의'와 '자료' 두 폴더가 생겨버린다."),
        ("만들고 바로 들어가기", "mkdir notes && cd notes", "&&는 앞 명령이 성공했을 때만 뒤 명령을 실행한다."),
    ],
    "rmdir": [
        ("빈 폴더 여러 개 정리", "rmdir old1 old2 old3", "셋 다 비어 있으면 한 번에 사라진다."),
        ("겹겹이 빈 폴더 거슬러 지우기", "rmdir -p a/b/c", "c를 지우고, 비었으면 b, 다시 비었으면 a까지 올라가며 지운다."),
        ("비어 보이는데 안 지워질 때", "ls -A photos", "Finder가 몰래 만든 .DS_Store 같은 숨김 파일이 보이면 그 때문이다."),
    ],
    "rm": [
        ("여러 파일 한꺼번에", "rm draft1.txt draft2.txt", "나열한 파일이 모두 삭제된다."),
        ("특정 확장자 전부", "rm *.log", "*는 '아무 글자나'라는 뜻. .log로 끝나는 파일이 모두 지워진다."),
        ("하나씩 확인하며 지우기", "rm -i *.jpg", "파일마다 remove? 라고 묻고, y를 눌러야 지운다."),
        ("이름이 -로 시작하는 파일", "rm -- -draft.txt", "-- 뒤는 옵션이 아니라 파일 이름이라는 약속이다."),
        ("휴지통으로 보내고 싶다면", "mv report.txt ~/.Trash/", "rm 대신 Finder 휴지통으로 옮기면 나중에 되살릴 수 있다."),
    ],
    "cp": [
        ("다른 폴더에 같은 이름으로", "cp report.txt ~/Documents/", "대상이 폴더면 원래 이름 그대로 그 안에 복사된다."),
        ("사진만 골라 복사", "cp *.jpg photos/", ".jpg 파일 전부가 photos 폴더로 복사된다."),
        ("수정 전 백업본 만들기", "cp config.json config.json.bak", "고치다 망가지면 .bak 파일로 되돌리면 된다."),
        ("있으면 건드리지 않기", "cp -n template.md README.md", "README.md가 이미 있으면 아무 일도 일어나지 않는다."),
        ("폴더 속 내용물만 복사", "cp -R src/ dest/", "macOS에서는 끝의 / 유무가 중요하다. src/는 내용물만, src는 폴더째 복사된다."),
    ],
    "mv": [
        ("확장자 바꾸기", "mv notes.txt notes.md", "내용은 그대로, 이름표만 바뀐다."),
        ("PDF만 모아서 이동", "mv *.pdf ~/Documents/", "현재 폴더의 PDF가 전부 문서 폴더로 옮겨진다."),
        ("한 단계 위 폴더로", "mv photo.jpg ..", "..는 '상위 폴더'를 뜻하는 약속이다."),
        ("덮어쓰기 사고 방지", "mv -n new.txt backup/", "backup/에 같은 이름이 있으면 옮기지 않는다."),
    ],
    "ls": [
        ("큰 파일부터 보기", "ls -lhS", "크기(S) 순으로, 사람이 읽기 좋은 단위(h)로 보여준다."),
        ("최근에 고친 파일 5개", "ls -lt | head -5", "|(파이프)는 앞 명령의 결과를 뒤 명령에 넘긴다. head는 앞부분만 자른다."),
        ("PNG 파일만", "ls *.png", "이름이 .png로 끝나는 것만 보여준다."),
        ("폴더만 골라 보기", "ls -d */", "끝이 /인 것, 즉 폴더만 나열한다."),
        ("한 줄에 하나씩", "ls -1", "다른 명령으로 넘기거나 개수를 셀 때 편하다. 숫자 1이다."),
    ],
    "find": [
        ("용량 먹는 범인 찾기", "find ~ -size +500M", "홈 폴더 전체에서 500MB가 넘는 파일을 찾는다."),
        ("특정 이름의 폴더만", 'find . -type d -name "node_modules"', "흩어져 있는 node_modules 폴더 위치를 한 번에 파악한다."),
        ("macOS 찌꺼기 청소", 'find . -name ".DS_Store" -delete', "Finder가 만든 .DS_Store 파일을 모두 지운다."),
        ("찾은 파일을 바탕화면으로", 'find . -name "*.png" -exec cp {} ~/Desktop/ \\;', "{}는 찾은 파일 하나하나, \\;는 명령의 끝을 뜻한다."),
        ("현재 폴더만 얕게", 'find . -maxdepth 1 -name "*.md"', "하위 폴더까지 파고들지 않고 지금 폴더만 본다."),
    ],
    "grep": [
        ("에러가 몇 번 났나", 'grep -c "error" app.log', "error가 들어간 줄의 개수만 숫자로 알려준다."),
        ("커밋 전 비밀키 점검", 'grep -rl "API_KEY" .', "API_KEY가 적힌 파일 이름만 뽑는다. 올리면 안 될 파일을 미리 찾는다."),
        ("앞뒤 사정까지 보기", 'grep -n -C 2 "Exception" app.log', "일치한 줄의 앞뒤 2줄을 줄 번호와 함께 보여준다."),
        ("둘 중 하나라도", 'grep -E "error|warn" app.log', "|는 '또는'. error나 warn이 있는 줄을 모두 찾는다."),
        ("예전에 친 명령 되찾기", "history | grep ssh", "입력 기록에서 ssh가 들어간 명령만 걸러낸다."),
        ("단어로만 찾기", 'grep -w "cat" notes.txt', "category나 concat은 빼고 cat이라는 단어만 찾는다."),
    ],
    "chmod": [
        ("스크립트를 실행 가능하게", "chmod +x build.sh", "이제 ./build.sh 로 바로 실행할 수 있다."),
        ("SSH 키를 나만 읽게", "chmod 600 ~/.ssh/id_ed25519", "키가 남에게 열려 있으면 ssh가 사용을 거부한다. 600은 나만 읽고 쓰기."),
        ("웹 폴더 권한 일괄 정리", "chmod -R 755 public/", "나는 모든 권한, 나머지는 읽기와 실행만."),
        ("그룹의 쓰기 권한만 빼기", "chmod g-w shared.txt", "그룹(g)에서 쓰기(w)를 뺀다(-). 나머지는 그대로."),
        ("바뀌었는지 확인", "ls -l build.sh", "-rwxr-xr-x 처럼 x가 보이면 실행 권한이 생긴 것이다."),
    ],
    "tar": [
        ("풀기 전에 안을 들여다보기", "tar -tzvf backup.tar.gz", "압축을 풀지 않고 들어 있는 파일 목록만 본다."),
        ("원하는 폴더에 풀기", "tar -xzvf backup.tar.gz -C ~/restore", "-C로 지정한 폴더 안에 풀린다. 폴더는 미리 있어야 한다."),
        ("여러 대상을 하나로", "tar -czvf site.tar.gz index.html css/ js/", "파일과 폴더를 섞어 한 파일로 묶는다."),
        ("무거운 폴더는 빼고", "tar -czvf project.tar.gz --exclude=node_modules project/", "다시 받을 수 있는 node_modules는 제외해 용량을 줄인다."),
        ("날짜가 붙은 백업 파일", "tar -czf docs-$(date +%Y%m%d).tar.gz docs/", "docs-20260930.tar.gz 처럼 날짜가 이름에 들어간다."),
    ],
    "curl": [
        ("이름을 바꿔 저장", "curl -o logo.png https://example.com/image.png", "소문자 o 뒤에 원하는 파일 이름을 적는다."),
        ("리다이렉트되는 링크 받기", "curl -LO https://example.com/latest.zip", "GitHub 릴리스처럼 주소가 한 번 옮겨지는 링크는 -L이 필요하다."),
        ("터미널에서 날씨 보기", "curl wttr.in/Seoul", "서울 날씨가 글자 그림으로 나온다. curl로 할 수 있는 가벼운 장난."),
        ("사이트가 살아 있나", 'curl -s -o /dev/null -w "%{http_code}" https://example.com', "200이면 정상, 404는 없음, 500번대는 서버 오류다."),
        ("API에 데이터 보내기", "curl -X POST -H \"Content-Type: application/json\" -d '{\"name\":\"kim\"}' https://api.example.com/users", "JSON 데이터를 POST 방식으로 서버에 보낸다."),
    ],
    "wget": [
        ("설치부터", "brew install wget", "macOS에는 기본으로 없으니 Homebrew로 설치한다."),
        ("끊긴 다운로드 이어받기", "wget -c https://example.com/big.iso", "받던 곳부터 이어서 받는다. 큰 파일에 유용하다."),
        ("이름을 정해서 저장", "wget -O data.csv https://example.com/export", "대문자 O 뒤에 저장할 이름을 적는다."),
        ("목록에 있는 파일 전부", "wget -i urls.txt", "한 줄에 하나씩 적힌 주소를 차례로 모두 받는다."),
    ],
    "ssh": [
        ("포트가 다른 서버", "ssh -p 2222 user@example.com", "관리자가 기본 22번 대신 다른 포트를 열어둔 경우다."),
        ("접속하지 않고 명령만", 'ssh user@example.com "df -h"', "서버의 디스크 상태만 받아오고 바로 연결을 끝낸다."),
        ("내 키 만들기", 'ssh-keygen -t ed25519 -C "me@example.com"', "~/.ssh/에 개인키와 공개키(.pub)가 생긴다."),
        ("비밀번호 없이 접속하게", "ssh-copy-id user@example.com", "내 공개키를 서버에 등록한다. 다음부터는 키로 자동 인증된다."),
        ("접속 끝내기", "exit", "원래 내 맥의 터미널로 돌아온다. Control+D도 같다."),
    ],
    "scp": [
        ("서버 파일을 내 맥으로", "scp user@example.com:~/log.txt ./", "콜론(:) 뒤가 서버 쪽 경로, ./는 지금 폴더다."),
        ("사진 여러 장 올리기", "scp *.jpg user@example.com:~/photos/", "현재 폴더의 jpg가 모두 서버로 올라간다."),
        ("포트가 다를 때", "scp -P 2222 file.txt user@example.com:~/", "ssh와 달리 대문자 P다."),
        ("별칭으로 짧게", "scp file.txt myserver:~/", "~/.ssh/config에 등록한 별칭을 그대로 쓸 수 있다."),
    ],
    "rsync": [
        ("외장하드로 백업", "rsync -av ~/Documents/ /Volumes/Backup/Documents/", "두 번째부터는 바뀐 파일만 복사돼 순식간에 끝난다."),
        ("무거운 폴더는 빼고", "rsync -av --exclude='node_modules' project/ backup/", "제외할 이름을 여러 번 지정할 수도 있다."),
        ("웹서버에 배포", "rsync -avz dist/ user@example.com:/var/www/html/", "빌드 결과물을 압축 전송해 서버에 올린다."),
        ("실행 전 리허설", "rsync -avn --delete src/ mirror/", "무엇이 복사되고 지워질지 목록만 보여준다. 확인 후 n을 뺀다."),
    ],
    "ps": [
        ("지금 이 창의 프로세스", "ps", "옵션 없이 쓰면 현재 터미널에서 띄운 것만 보인다."),
        ("CPU를 가장 많이 쓰는 5개", "ps aux -r | head -6", "맥이 느려졌을 때 범인을 찾는 가장 빠른 방법 (첫 줄은 제목)."),
        ("메모리 대식가 찾기", "ps aux -m | head -6", "메모리 사용량 순으로 정렬한다."),
        ("실시간으로 지켜보기", "top -o cpu", "계속 갱신되는 화면. q로 빠져나온다."),
    ],
    "kill": [
        ("3000번 포트를 쥔 범인", "lsof -i :3000", "개발 서버가 안 켜질 때, 그 포트를 붙잡은 프로세스의 PID를 알려준다."),
        ("찾자마자 종료", "kill $(lsof -t -i :3000)", "-t는 PID만 출력. 그 번호를 바로 kill에 넘긴다."),
        ("응답 없는 앱 닫기", "killall Safari", "이름이 같은 프로세스를 모두 종료한다."),
        ("명령어 일부로 찾아 종료", 'pkill -f "node server.js"', "-f는 실행 명령 전체 문자열에서 찾는다."),
        ("보낼 수 있는 신호 목록", "kill -l", "HUP INT QUIT ... 같은 신호 이름이 나열된다."),
    ],
    "diff": [
        ("좌우로 나란히", "diff -y old.txt new.txt", "두 파일을 양쪽에 놓고 다른 줄에 표시를 붙인다."),
        ("두 폴더에서 다른 파일만", "diff -rq folder1 folder2", "내용은 생략하고 어떤 파일이 다른지만 알려준다."),
        ("띄어쓰기 차이는 무시", "diff -w a.py b.py", "들여쓰기나 공백만 다른 줄은 같다고 본다."),
        ("변경 내역을 파일로", "diff -u old.txt new.txt > changes.patch", "> 는 결과를 파일로 저장. 이 patch 파일로 남에게 수정 사항을 전달한다."),
        ("두 폴더의 목록 비교", "diff <(ls dir1) <(ls dir2)", "<( )는 명령 결과를 임시 파일처럼 넘기는 zsh 문법이다."),
    ],
    "du": [
        ("용량 순위 TOP 10", "du -sh * | sort -rh | head -10", "현재 폴더에서 가장 무거운 항목 10개."),
        ("홈 폴더 한 단계만", "du -h -d 1 ~", "하위 폴더별 합계만 보여준다. 어디가 무거운지 큰 그림을 본다."),
        ("캐시가 얼마나 쌓였나", "du -sh ~/Library/Caches", "앱들이 쌓아둔 캐시 용량. 수 GB인 경우도 흔하다."),
        ("node_modules의 무게", "du -sh node_modules", "프로젝트 하나에 수백 MB가 나오기도 한다."),
    ],
    "df": [
        ("맥 본체 디스크만", "df -h /", "가장 자주 보는 형태. Avail이 남은 공간이다."),
        ("Finder와 같은 숫자로", "df -H /", "Finder는 1000 단위로 계산한다. 숫자가 다르게 보일 때 이걸 쓴다."),
        ("외장하드 남은 공간", "df -h /Volumes/Backup", "연결된 외장 디스크는 /Volumes 아래에 있다."),
        ("지금 폴더가 속한 디스크", "df -h .", ".은 현재 폴더. 이 폴더가 있는 디스크 정보를 보여준다."),
    ],
    "alias": [
        ("자주 가는 폴더로 순간이동", "alias proj='cd ~/Projects'", "이제 proj만 치면 프로젝트 폴더로 이동한다."),
        ("삭제 전 확인을 기본으로", "alias rm='rm -i'", "실수 방지용 안전장치. 급할 땐 \\rm으로 원래 rm을 쓴다."),
        ("git 명령 줄이기", "alias gs='git status'", "하루에 수십 번 치는 명령일수록 효과가 크다."),
        ("이 이름의 정체 확인", "type ll", "ll is an alias for ls -lah 처럼 무엇의 별명인지 알려준다."),
        ("영구 등록을 한 줄로", "echo \"alias ll='ls -lah'\" >> ~/.zshrc", ">>는 파일 끝에 덧붙이기. 적용하려면 source ~/.zshrc."),
    ],
    "export": [
        ("내 스크립트 폴더를 PATH에", 'export PATH="$HOME/bin:$PATH"', "~/bin 안의 프로그램을 어느 폴더에서든 이름만으로 실행할 수 있다."),
        ("이 명령에만 잠깐", "NODE_ENV=test npm test", "export 없이 앞에 붙이면 그 명령 한 번에만 적용된다."),
        ("기본 편집기 정하기", "export EDITOR=nano", "git 커밋 메시지 등을 쓸 때 nano가 열린다."),
        ("값 확인하기", "printenv HOME", "/Users/me 처럼 변수의 값만 출력한다."),
        ("변수 지우기", "unset NODE_ENV", "현재 창에서 그 변수가 사라진다."),
    ],
    "source": [
        ("설정 바로 적용", "source ~/.zshrc", "alias나 PATH를 고친 뒤 새 창을 열 필요가 없다."),
        ("파이썬 가상환경 켜기", "source .venv/bin/activate", "프롬프트 앞에 (.venv)가 붙으면 성공이다."),
        ("별명 파일 따로 관리", "source ~/.aliases", ".zshrc 안에 이 줄을 넣어 두면 별명만 모은 파일을 따로 관리할 수 있다."),
        (".env를 환경변수로", "set -a; source .env; set +a", "set -a는 이후 만드는 변수를 자동으로 export한다."),
    ],
}


QUICKREF = {
    "01": [("mkdir -p a/b/c", "중첩 폴더를 한 번에 만들기"),
           ("rmdir 폴더", "빈 폴더 지우기"),
           ("rm -i 파일", "하나씩 확인하며 삭제"),
           ("rm -r 폴더", "폴더째 삭제 (되돌릴 수 없음)"),
           ("cp 원본 사본", "파일 복사"),
           ("cp -R 원본/ 대상/", "폴더 내용물 복사"),
           ("mv 옛이름 새이름", "이름 바꾸기"),
           ("mv *.pdf 폴더/", "여러 파일 한꺼번에 이동"),
           ("ls -lah", "숨김 파일까지 자세히 보기"),
           ("ls -lt | head", "최근 수정한 파일부터 보기")],
    "02": [('find . -name "*.txt"', "이름으로 파일 찾기"),
           ("find ~ -size +500M", "큰 파일 찾기"),
           ('find . -name ".DS_Store" -delete', "찾아서 바로 지우기"),
           ('grep -rn "단어" .', "폴더 전체에서 글자 찾기 (줄 번호 포함)"),
           ('grep -rl "단어" .', "그 글자가 든 파일 이름만"),
           ("history | grep ssh", "예전에 쓴 명령 찾기")],
    "03": [("chmod +x 파일", "실행할 수 있게 만들기"),
           ("chmod 600 파일", "나만 읽고 쓰기 (SSH 키 등)"),
           ("chmod 755 파일", "나는 전부, 남은 읽기·실행만"),
           ("chmod -R 755 폴더", "폴더 안쪽 전체에 적용"),
           ("ls -l 파일", "현재 권한 확인")],
    "04": [("tar -czvf 이름.tar.gz 대상", "압축하기"),
           ("tar -xzvf 이름.tar.gz", "압축 풀기"),
           ("tar -xzvf 이름.tar.gz -C 폴더", "원하는 폴더에 풀기"),
           ("tar -tzvf 이름.tar.gz", "풀지 않고 내용만 보기"),
           ("--exclude=node_modules", "특정 폴더를 빼고 압축")],
    "05": [("curl -LO 주소", "파일 다운로드"),
           ("curl -I 주소", "응답 헤더만 확인"),
           ("wget -c 주소", "끊긴 다운로드 이어받기"),
           ("ssh user@host", "서버에 접속"),
           ("ssh-keygen -t ed25519", "SSH 키 만들기"),
           ("scp 파일 user@host:경로", "서버로 파일 보내기"),
           ("rsync -av 원본/ 대상/", "바뀐 파일만 동기화"),
           ("rsync -avn --delete 원본/ 대상/", "동기화 결과 미리보기")],
    "06": [("ps aux | grep 이름", "특정 프로세스 찾기"),
           ("ps aux -r | head", "CPU를 많이 쓰는 순서"),
           ("top -o cpu", "실시간으로 지켜보기 (q로 종료)"),
           ("kill PID", "정상 종료 요청"),
           ("kill -9 PID", "강제 종료"),
           ("lsof -i :3000", "포트를 쓰는 프로세스 찾기"),
           ("killall 앱이름", "이름으로 모두 종료")],
    "07": [("diff -u a b", "두 파일의 차이 보기"),
           ("diff -rq 폴더1 폴더2", "다른 파일 목록만"),
           ("du -sh * | sort -rh", "무거운 항목 순위"),
           ("du -h -d 1 ~", "홈 폴더를 폴더별 용량으로"),
           ("df -h /", "디스크 남은 공간"),
           ("df -H /", "Finder와 같은 단위로 보기")],
    "08": [("alias ll='ls -lah'", "긴 명령에 별명 붙이기"),
           ("type 이름", "별명의 정체 확인"),
           ('export PATH="$HOME/bin:$PATH"', "PATH에 폴더 추가"),
           ("echo $변수", "변수 값 보기"),
           ("unset 변수", "변수 지우기"),
           ("source ~/.zshrc", "바꾼 설정을 바로 적용")],
}

# (group, [(situation, [(label, marker_key), ...])])
K = lambda *cmds: [(x, f"PM_CMD_{x}") for x in cmds]
INDEX = [
    ("이동과 파일", [
        ("지금 어느 폴더에 있는지 모르겠다", K("pwd")),
        ("다른 폴더로 이동하고 싶다", K("cd")),
        ("폴더 안에 뭐가 있는지 보고 싶다", K("ls")),
        ("숨김 파일까지 보고 싶다", K("ls")),
        ("새 폴더를 만들고 싶다", K("mkdir")),
        ("빈 파일을 만들고 싶다", K("touch")),
        ("파일이나 폴더를 지우고 싶다", K("rm", "rmdir")),
        ("지워도 나중에 되살릴 수 있게 하고 싶다", K("rm")),
        ("파일을 복사하거나 백업본을 만들고 싶다", K("cp", "rsync")),
        ("파일을 옮기거나 이름을 바꾸고 싶다", K("mv")),
        ("바로가기(링크)를 만들고 싶다", K("ln")),
    ]),
    ("내용 보기와 가공", [
        ("파일 내용을 바로 보고 싶다", K("cat")),
        ("긴 파일을 천천히 넘겨 보고 싶다", K("less")),
        ("파일 앞부분이나 끝부분만 보고 싶다", K("head", "tail")),
        ("로그를 실시간으로 지켜보고 싶다", K("tail")),
        ("파일에 한 줄 써 넣고 싶다", K("echo")),
        ("줄 수나 글자 수를 세고 싶다", K("wc")),
        ("목록을 정렬하고 중복을 없애고 싶다", K("sort")),
        ("파일 속 글자를 한꺼번에 바꾸고 싶다", K("sed")),
        ("찾은 파일들에 한 번에 명령하고 싶다", K("xargs")),
    ]),
    ("찾기", [
        ("파일이 어디 있는지 모르겠다", K("find", "mdfind")),
        ("파일 속 특정 글자를 찾고 싶다", K("grep")),
        ("설치한 프로그램이 어디 있는지 알고 싶다", K("which")),
        ("예전에 쓴 명령을 다시 찾고 싶다", K("history", "grep")),
        ("명령어 사용법을 모르겠다", K("man")),
    ]),
    ("권한과 압축", [
        ("Permission denied 오류가 난다", K("chmod", "chown")),
        ("관리자 권한이 필요하다고 나온다", K("sudo")),
        ("비밀번호를 쳐도 화면에 안 보인다", K("sudo")),
        ("SSH 키 권한 경고가 뜬다", K("chmod", "ssh")),
        ("여러 파일을 하나로 묶고 싶다", K("tar", "zip")),
        ("윈도우 사용자에게 압축해서 보내고 싶다", K("zip")),
        ("압축 파일을 풀고 싶다", K("tar", "zip")),
    ]),
    ("인터넷과 서버", [
        ("인터넷이 연결됐는지 확인하고 싶다", K("ping")),
        ("인터넷에서 파일을 받고 싶다", K("curl", "wget")),
        ("API를 테스트하고 싶다", K("curl")),
        ("서버에 접속하고 싶다", K("ssh")),
        ("서버와 파일을 주고받고 싶다", K("scp", "rsync")),
        ("외장하드에 백업하고 싶다", K("rsync")),
    ]),
    ("맥의 상태", [
        ("맥이 갑자기 느려졌다", K("top", "ps")),
        ("앱이 응답하지 않는다", K("kill")),
        ("포트가 이미 사용 중이라고 나온다", K("lsof", "kill")),
        ("외장하드가 추출되지 않는다", K("lsof")),
        ("실행 중인 명령을 멈추고 싶다", [("Control+C", "PM_BASICS")]),
        ("디스크 공간이 부족하다", K("df", "du", "find")),
        ("두 파일이 어디가 다른지 보고 싶다", K("diff")),
    ]),
    ("터미널 환경과 맥 전용", [
        ("자주 쓰는 긴 명령을 줄이고 싶다", K("alias")),
        ("설치했는데 command not found가 뜬다", K("which", "export")),
        ("설정을 바꿨는데 적용이 안 된다", K("source")),
        ("터미널에서 Finder로 넘어가고 싶다", K("open")),
        ("명령 결과를 클립보드에 복사하고 싶다", K("pbcopy")),
        ("작업 중에 맥이 잠들지 않게 하고 싶다", K("caffeinate")),
        ("작업이 끝나면 소리로 알림을 받고 싶다", K("say")),
    ]),
]
