# 27 additional commands. term lines: ("cmd", text) / ("out", text) / ("arrow", text)
NEW = {
"pwd": dict(
    full="print working directory", syntax="pwd",
    oneliner="지금 내가 서 있는 폴더를 알려준다.",
    term=[("cmd", "pwd"), ("out", "/Users/me/Documents/lecture")],
    origin="print working directory. \"지금 작업 중인 폴더를 출력하라\"는 뜻이다. 여기서 print가 프린터를 뜻하지 않는데도 굳이 print인 이유는, 텔레타이프 시절에는 결과가 정말로 종이에 인쇄되어 나왔기 때문이다.",
    options=[("-P", "<b>P</b>hysical", "바로가기(링크)를 풀어 실제 경로로"),
             ("-L", "<b>L</b>ogical", "링크 경로 그대로 (기본값)")],
    examples=[("길을 잃었을 때", "pwd", "프롬프트의 ~ 표시만으로 헷갈릴 때 전체 경로를 확인한다."),
              ("경로를 복사해 두기", "pwd | pbcopy", "현재 경로가 클립보드에 들어간다. 메신저에 바로 붙여넣을 수 있다."),
              ("링크 뒤의 진짜 위치", "pwd -P", "바로가기로 들어온 폴더라면 실제 폴더 경로가 나온다.")],
    callouts=[("mnemonic", "p-w-d를 \"폴더 위치 답해\"로 외워도 좋다. 원래 뜻은 print working directory."),
              ("tip", "Finder에서 폴더를 터미널 창에 끌어다 놓으면 그 폴더의 전체 경로가 자동으로 입력된다. pwd와 반대 방향의 요령이다.")]),

"cd": dict(
    full="change directory", syntax="cd [경로]",
    oneliner="다른 폴더로 이동한다.",
    term=[("cmd", "cd Documents"), ("arrow", "프롬프트가 ~/Documents % 로 바뀜"),
          ("cmd", "cd .."), ("arrow", "한 단계 위 폴더로")],
    origin="change directory. 초기 유닉스 셸에서는 chdir이라는 조금 더 긴 이름이었다가, 가장 자주 치는 명령답게 두 글자 cd로 줄었다.",
    options=[("~", "tilde = <b>home</b>", "내 홈 폴더"),
             ("..", "parent", "한 단계 위 폴더"),
             ("-", "previous", "바로 직전에 있던 폴더"),
             ("/", "root", "디스크의 맨 꼭대기")],
    options_label="특별한 경로 기호",
    examples=[("어디서든 집으로", "cd", "아무것도 안 붙이면 홈 폴더로 돌아간다. cd ~와 같다."),
              ("두 폴더를 왔다 갔다", "cd -", "직전 폴더로 돌아간다. 한 번 더 치면 다시 원래 자리로."),
              ("이름에 공백이 있을 때", 'cd "My Projects"', "따옴표로 감싸거나 My\\ Projects처럼 공백 앞에 \\를 붙인다."),
              ("두 단계 위로", "cd ../..", "..를 /로 이어 붙이면 여러 단계를 한 번에 올라간다."),
              ("Tab으로 빠르게", "cd Doc + Tab", "폴더 이름 앞 몇 글자만 치고 Tab을 누르면 나머지가 채워진다.")],
    callouts=[("story", "cd는 프로그램 파일이 아니라 셸에 내장된 명령이다. 별도 프로그램으로 만들면 그 프로그램 안에서만 폴더가 바뀌고, 끝나는 순간 원래 자리로 돌아와 버리기 때문이다. \"내 위치를 바꾸는 일은 나만 할 수 있다\"는 유닉스 설계의 작은 철학이다."),
              ("tip", "Finder의 폴더를 터미널 창으로 끌어다 놓으면 경로가 입력된다. cd 한 칸 띄우고 폴더를 끌어다 놓으면 끝.")]),

"touch": dict(
    full="touch (살짝 건드리다)", syntax="touch 파일명",
    oneliner="빈 파일을 만들거나 수정 시각을 지금으로 바꾼다.",
    term=[("cmd", "touch index.html"), ("cmd", "ls -l index.html"),
          ("out", "-rw-r--r--  1 me  staff  0  9 30 10:02 index.html")],
    origin="touch는 \"살짝 건드리다\"라는 뜻이다. 원래 목적은 파일을 열지 않고 살짝 건드려 수정 시각만 지금으로 바꾸는 것이었다. 파일이 없으면 새로 만들어 주는 부수 효과가 오히려 더 유명해졌다.",
    options=[("-c", "no-<b>c</b>reate", "없는 파일은 만들지 않음"),
             ("-t", "<b>t</b>ime", "원하는 날짜·시각으로 지정"),
             ("-a", "<b>a</b>ccess time", "마지막으로 연 시각만 변경"),
             ("-m", "<b>m</b>odification time", "수정 시각만 변경")],
    examples=[("파일 여러 개 한 번에", "touch index.html style.css app.js", "크기 0짜리 빈 파일 세 개가 생긴다."),
              ("번호 붙은 파일 만들기", "touch page{1..5}.md", "page1.md부터 page5.md까지 한꺼번에 생긴다."),
              ("빈 폴더를 git에 올리려면", "touch assets/.gitkeep", "git은 빈 폴더를 기록하지 않아서, 이름뿐인 파일을 하나 넣어 두는 관례다."),
              ("날짜를 과거로 되돌리기", "touch -t 202601010900 memo.txt", "수정 시각이 2026년 1월 1일 9시로 바뀐다.")],
    callouts=[("story", "빌드 도구 make는 파일의 수정 시각을 보고 다시 컴파일할지 결정한다. 그래서 개발자들은 내용은 그대로 두고 touch로 파일을 \"건드려\" 강제로 다시 빌드시키곤 했다. 이름이 기능을 그대로 설명하는 드문 명령어다.")]),

"cat": dict(
    full="concatenate", syntax="cat 파일명",
    oneliner="파일 내용을 화면에 쏟아낸다.",
    term=[("cmd", "cat hello.txt"), ("out", "안녕하세요."), ("out", "터미널에 오신 것을 환영합니다.")],
    origin="concatenate(사슬처럼 이어 붙이다)에서 왔다. 원래 목적은 여러 파일을 이어 붙이는 것이었고, 파일 하나만 주면 그냥 내용을 보여주게 된다. 고양이(cat)와는 아무 관계가 없지만, 덕분에 개발자 굿즈에 고양이가 자주 등장한다.",
    options=[("-n", "<b>n</b>umber", "모든 줄에 번호 붙이기"),
             ("-b", "num<b>b</b>er non-blank", "빈 줄 빼고 번호 붙이기"),
             ("-s", "<b>s</b>queeze", "연속된 빈 줄을 하나로")],
    examples=[("두 파일을 하나로 합치기", "cat part1.txt part2.txt > full.txt", "이름 그대로 이어 붙이는 원래 용도다. >는 결과를 파일로 저장."),
              ("줄 번호와 함께 보기", "cat -n script.sh", "오류 메시지가 \"12번째 줄\"을 가리킬 때 찾기 쉽다."),
              ("짧은 메모 바로 쓰기", "cat > memo.txt", "내용을 입력하고 Control+D를 누르면 저장된다."),
              ("숨은 설정 파일 확인", "cat ~/.zshrc", "지금 적용된 zsh 설정을 한눈에 본다.")],
    callouts=[("tip", "수백 줄이 넘는 파일을 cat으로 열면 화면이 순식간에 지나가 버린다. 긴 파일은 less로 여는 편이 낫다."),
              ("story", "cat file | grep 단어 처럼 굳이 cat을 거치는 습관은 개발자들 사이에서 \"쓸모없는 cat 사용상(Useless Use of Cat Award)\"이라는 농담의 대상이 됐다. grep 단어 file 한 번이면 충분하기 때문이다.")]),

"less": dict(
    full="less is more", syntax="less 파일명",
    oneliner="긴 파일을 한 화면씩 넘겨 본다.",
    term=[("cmd", "less app.log"), ("arrow", "한 화면씩 표시, Space로 넘기고 q로 종료")],
    origin="예전부터 한 화면씩 끊어 보여주는 more라는 명령이 있었다. 1980년대 중반 마크 누델먼이 뒤로 되돌아가기까지 되는 개량판을 만들며 \"less is more(적은 것이 더 많다)\"라는 말장난으로 이름을 less라 붙였다.",
    options=[("Space / b", "forward · <b>b</b>ack", "다음 화면 · 이전 화면"),
             ("/단어", "search", "아래로 검색"),
             ("n / N", "<b>n</b>ext", "다음 · 이전 검색 결과"),
             ("g / G", "<b>g</b>o", "맨 처음 · 맨 끝으로"),
             ("F", "<b>F</b>ollow", "새로 추가되는 줄을 계속 따라감"),
             ("q", "<b>q</b>uit", "나가기")],
    options_label="less 안에서 쓰는 키",
    examples=[("로그를 실시간으로", "less +F app.log", "tail -f처럼 새 줄을 따라간다. Control+C로 멈추면 자유롭게 스크롤할 수 있다."),
              ("긴 명령 결과 넘겨 보기", "ls -la /usr/bin | less", "결과가 화면을 넘어갈 때 뒤에 | less를 붙이는 습관."),
              ("줄 번호와 함께", "less -N config.yml", "왼쪽에 줄 번호가 붙는다."),
              ("검색하며 읽기", "/ERROR", "less 화면에서 /를 누르고 단어를 치면 해당 위치로 이동한다.")],
    callouts=[("mnemonic", "more보다 기능이 많은데 이름은 less. \"less is more\" 농담만 기억하면 이름이 저절로 떠오른다."),
              ("tip", "man 명령으로 여는 설명서 화면도 사실 less다. 그래서 설명서 안에서도 /검색과 q 종료가 똑같이 통한다.")]),

"head": dict(
    full="head (머리)", syntax="head [-n 줄수] 파일명",
    oneliner="파일의 앞부분만 보여준다.",
    term=[("cmd", "head -n 3 data.csv"), ("out", "name,age,city"), ("out", "kim,31,Seoul"), ("out", "lee,28,Busan")],
    origin="head, 즉 머리. 파일의 머리 부분(앞 10줄)을 보여준다. 꼬리를 보여주는 tail과 짝을 이룬다.",
    options=[("-n", "<b>n</b>umber of lines", "앞에서 몇 줄 볼지 (기본 10)"),
             ("-c", "bytes (<b>c</b>haracters)", "앞에서 몇 바이트 볼지")],
    examples=[("CSV의 제목 줄만", "head -1 data.csv", "어떤 열이 있는지 파일을 열지 않고 확인한다."),
              ("최근 파일 5개", "ls -lt | head -5", "다른 명령 결과의 앞부분만 자를 때 가장 많이 쓴다."),
              ("거대한 파일 맛보기", "head -n 20 huge.log", "수 GB짜리 파일도 앞 20줄만 순식간에 본다.")],
    callouts=[("mnemonic", "head는 머리, tail은 꼬리. 파일을 동물이라고 생각하면 절대 안 헷갈린다.")]),

"tail": dict(
    full="tail (꼬리)", syntax="tail [-n 줄수] 파일명",
    oneliner="파일의 끝부분만 보여준다. 실시간 추적도 된다.",
    term=[("cmd", "tail -f server.log"), ("out", "10:02:11 GET /index.html 200"), ("out", "10:02:14 GET /api/users 200"),
          ("arrow", "새 줄이 생길 때마다 계속 출력, Control+C로 종료")],
    origin="tail, 즉 꼬리. 파일의 마지막 10줄을 보여준다. -f(follow) 옵션 덕분에 서버 관리자들이 가장 오래 켜두는 명령이 되었다.",
    options=[("-n", "<b>n</b>umber of lines", "끝에서 몇 줄 볼지 (기본 10)"),
             ("-f", "<b>f</b>ollow", "새로 추가되는 줄을 계속 출력"),
             ("-F", "<b>F</b>ollow (retry)", "파일이 새로 바뀌어도 계속 추적"),
             ("-r", "<b>r</b>everse", "마지막 줄부터 거꾸로")],
    examples=[("마지막 20줄", "tail -n 20 app.log", "방금 무슨 일이 있었는지 확인할 때."),
              ("에러만 실시간으로", "tail -f app.log | grep ERROR", "로그가 쌓이는 동안 ERROR가 들어간 줄만 걸러 본다."),
              ("제목 줄 빼고 전부", "tail -n +2 data.csv", "+2는 \"2번째 줄부터\"라는 뜻. CSV 데이터만 뽑을 때 유용하다.")],
    callouts=[("tip", "tail -f 로그 | grep 키워드 는 서버 문제를 추적할 때 가장 많이 쓰는 조합이다. 외워 둘 가치가 있다.")]),

"open": dict(
    full="open (macOS 전용)", syntax="open 파일|폴더|주소",
    oneliner="Finder에서 더블클릭한 것처럼 연다.",
    term=[("cmd", "open ."), ("arrow", "지금 폴더가 Finder 창으로 열림"),
          ("cmd", "open report.pdf"), ("arrow", "미리보기 앱으로 열림")],
    origin="이름 그대로 \"열기\". 맥의 뿌리인 NeXTSTEP 시절부터 이어진 macOS 전용 명령이다. 리눅스에는 없어서 맥 사용자의 특권 같은 명령이다.",
    options=[("-a", "<b>a</b>pplication", "지정한 앱으로 열기"),
             ("-e", "T<b>e</b>xtEdit", "텍스트 편집기로 열기"),
             ("-R", "<b>R</b>eveal", "Finder에서 위치만 보여주기"),
             ("-n", "<b>n</b>ew instance", "앱을 새 창(새 인스턴스)으로")],
    examples=[("터미널에서 Finder로", "open .", ".은 현재 폴더. 터미널과 Finder를 오가는 가장 빠른 길이다."),
              ("VS Code로 프로젝트 열기", 'open -a "Visual Studio Code" .', "앱 이름에 공백이 있으면 따옴표로 감싼다."),
              ("웹사이트 열기", "open https://www.apple.com", "기본 브라우저로 주소가 열린다."),
              ("파일 위치 보여주기", "open -R ~/Downloads/report.pdf", "파일을 열지 않고 Finder에서 선택된 상태로 보여준다.")],
    callouts=[("tip", "open .은 맥 사용자들이 가장 사랑하는 명령 중 하나다. 터미널 작업 중에 \"이 폴더 Finder로 보고 싶다\" 싶으면 바로 치면 된다.")]),

"echo": dict(
    full="echo (메아리)", syntax="echo 문자열",
    oneliner="입력한 말을 그대로 되돌려준다.",
    term=[("cmd", 'echo "안녕, 터미널"'), ("out", "안녕, 터미널"),
          ("cmd", "echo $HOME"), ("out", "/Users/me")],
    origin="echo, 메아리. 외친 말을 그대로 돌려주는 메아리처럼, 받은 글자를 화면에 그대로 출력한다. 단순해 보이지만 변수 확인과 파일 쓰기에 매일 쓰인다.",
    options=[("-n", "<b>n</b>o newline", "끝에 줄바꿈을 붙이지 않음"),
             (">", "redirect", "결과를 파일에 덮어쓰기"),
             (">>", "append", "결과를 파일 끝에 덧붙이기")],
    examples=[("변수 값 확인", "echo $PATH", "프로그램을 찾는 경로 목록이 나온다."),
              ("파일에 한 줄 쓰기", 'echo "첫 줄" > note.txt', "note.txt가 없으면 만들고, 있으면 내용을 덮어쓴다."),
              ("파일 끝에 덧붙이기", 'echo "둘째 줄" >> note.txt', "기존 내용은 그대로 두고 아래에 추가한다."),
              ("방금 명령이 성공했나", "echo $?", "0이면 성공, 그 외 숫자면 실패다.")],
    callouts=[("tip", "> 는 덮어쓰기, >> 는 덧붙이기. 한 글자 차이로 파일 내용이 통째로 사라질 수 있으니 설정 파일에 쓸 때는 특히 >>인지 확인하자.")]),

"wc": dict(
    full="word count", syntax="wc [옵션] 파일명",
    oneliner="줄, 단어, 글자 수를 센다.",
    term=[("cmd", "wc essay.txt"), ("out", "      42     318    2204 essay.txt"), ("arrow", "줄 42 · 단어 318 · 바이트 2204")],
    origin="word count. 이름은 단어 세기지만 줄과 바이트까지 한 번에 세어 준다.",
    options=[("-l", "<b>l</b>ines", "줄 수만"),
             ("-w", "<b>w</b>ords", "단어 수만"),
             ("-c", "bytes (<b>c</b>haracters)", "바이트 수만"),
             ("-m", "<b>m</b>ultibyte characters", "실제 글자 수 (한글 포함)")],
    examples=[("데이터가 몇 줄인가", "wc -l data.csv", "CSV라면 제목 줄 포함 행 개수다."),
              ("파일이 몇 개인가", "ls | wc -l", "ls 결과를 한 줄에 하나씩 세면 파일 개수가 된다."),
              ("코드가 몇 줄인가", "cat src/*.ts | wc -l", "프로젝트 규모를 가늠할 때 쓴다."),
              ("한글 글자 수 세기", "wc -m essay.txt", "한글은 한 글자가 3바이트라 -c로 세면 세 배로 나온다. 글자 수는 -m.")],
    callouts=[("tip", "원고 분량을 셀 때 wc -m이 유용하다. 공백과 줄바꿈도 한 글자로 세므로 \"공백 포함 글자 수\"와 같다.")]),

"sort": dict(
    full="sort (정렬하다)", syntax="sort [옵션] 파일명",
    oneliner="줄을 순서대로 정렬한다.",
    term=[("cmd", "sort fruits.txt"), ("out", "apple"), ("out", "banana"), ("out", "cherry")],
    origin="sort, 정렬하다. 기본은 글자 순서(사전 순)라서 숫자를 정렬할 때는 옵션이 필요하다.",
    options=[("-n", "<b>n</b>umeric", "숫자 크기 순"),
             ("-r", "<b>r</b>everse", "거꾸로 (큰 것부터)"),
             ("-h", "<b>h</b>uman numeric", "1K, 2M, 3G 같은 단위 숫자 순"),
             ("-u", "<b>u</b>nique", "중복 줄 제거"),
             ("-k", "<b>k</b>ey", "몇 번째 열을 기준으로"),
             ("-t", "field separa<b>t</b>or", "열을 나누는 기호 지정")],
    examples=[("숫자를 제대로 정렬", "sort -n scores.txt", "-n이 없으면 10이 2보다 앞에 온다. 글자 \"1\"이 \"2\"보다 앞이기 때문."),
              ("중복 없이 정리", "sort -u emails.txt", "같은 이메일이 여러 번 있어도 한 번씩만 남는다."),
              ("가장 많이 나온 순위", "sort access.log | uniq -c | sort -rn | head", "같은 줄끼리 모으고(sort), 개수를 세고(uniq -c), 많은 순으로 다시 정렬한다."),
              ("CSV 둘째 열 기준", "sort -t, -k2 data.csv", "쉼표(,)로 열을 나누고 2번째 열로 정렬한다."),
              ("용량 순 정렬", "du -sh * | sort -rh", "-h는 1.2G와 48M 같은 단위를 이해한다.")],
    callouts=[("story", "짝꿍 명령 uniq는 \"바로 붙어 있는\" 중복만 지운다. 그래서 거의 언제나 sort | uniq 순서로 함께 쓰인다. 두 글자로 말하는 사람들의 문장이 파이프(|)로 이어지는 대표적인 예다.")]),

"ln": dict(
    full="link", syntax="ln -s 원본 링크이름",
    oneliner="파일이나 폴더의 바로가기를 만든다.",
    term=[("cmd", "ln -s ~/Dropbox/notes ~/notes"), ("cmd", "ls -l ~/notes"),
          ("out", "lrwxr-xr-x  1 me  staff  27 ... notes -> /Users/me/Dropbox/notes")],
    origin="link를 줄인 이름. -s를 붙이면 심볼릭 링크(바로가기), 붙이지 않으면 하드 링크(같은 파일에 이름을 하나 더 붙이기)가 된다.",
    options=[("-s", "<b>s</b>ymbolic", "바로가기 형태의 링크 (대부분 이것)"),
             ("-f", "<b>f</b>orce", "같은 이름이 있으면 바꿔치기"),
             ("-v", "<b>v</b>erbose", "만든 링크 표시")],
    examples=[("자주 가는 깊은 폴더를 가까이", "ln -s ~/Library/Mobile\\ Documents/com~apple~CloudDocs ~/iCloud", "iCloud Drive처럼 깊숙한 폴더를 홈에서 바로 연다."),
              ("설정 파일 한곳에서 관리", "ln -s ~/dotfiles/.zshrc ~/.zshrc", "설정을 git 폴더에 두고 링크만 걸어 여러 컴퓨터에서 공유한다."),
              ("링크가 가리키는 곳 확인", "ls -l ~/notes", "-> 뒤에 원본 경로가 표시된다."),
              ("링크만 지우기", "rm ~/notes", "원본은 안전하다. 단, 끝에 /를 붙여 rm -r ~/notes/ 로 지우면 원본 내용이 지워질 수 있다.")],
    callouts=[("mnemonic", "순서는 cp와 같다. \"진짜 먼저, 가짜 나중\". ln -s 원본 바로가기."),
              ("story", "Finder에서 만드는 \"가상본(alias)\"은 이름은 비슷하지만 터미널의 심볼릭 링크와 다른 물건이다. Finder 가상본으로는 cd로 들어갈 수 없다. 터미널에서 쓸 바로가기는 ln -s로 만들어야 한다.")]),

"mdfind": dict(
    full="metadata find (macOS 전용)", syntax='mdfind "검색어"',
    oneliner="Spotlight의 색인으로 순식간에 찾는다.",
    term=[("cmd", 'mdfind "분기 보고서"'), ("out", "/Users/me/Documents/2026-Q3 분기 보고서.pdf"),
          ("out", "/Users/me/Desktop/보고서 초안.docx")],
    origin="metadata find. md는 메타데이터(파일에 대한 정보)를 뜻한다. Cmd+Space로 쓰는 Spotlight가 미리 만들어 둔 색인을 터미널에서 검색하는 명령이다.",
    options=[("-name", "<b>name</b>", "파일 이름에서만 찾기"),
             ("-onlyin", "<b>only in</b>", "특정 폴더 안에서만"),
             ("-count", "<b>count</b>", "결과 개수만"),
             ("-live", "<b>live</b>", "새 결과가 생기면 계속 표시")],
    examples=[("파일 이름으로", 'mdfind -name "invoice"', "이름에 invoice가 들어간 파일을 디스크 전체에서 찾는다."),
              ("특정 폴더에서 내용으로", 'mdfind -onlyin ~/Documents "계약서"', "문서 안에 \"계약서\"라는 단어가 있는 파일까지 찾는다."),
              ("PDF가 몇 개인가", 'mdfind -count "kind:pdf"', "kind: 뒤에 종류를 적으면 파일 형식으로 거른다.")],
    callouts=[("tip", "find는 디스크를 직접 한 칸씩 뒤져 느리지만, mdfind는 색인을 보기 때문에 거의 즉시 끝난다. 대신 Spotlight에서 제외한 폴더는 찾지 못한다.")]),

"which": dict(
    full="which (어느 것)", syntax="which 명령어",
    oneliner="그 명령어가 실제로 어디 있는 프로그램인지 알려준다.",
    term=[("cmd", "which python3"), ("out", "/usr/bin/python3")],
    origin="which, \"어느 것\". 같은 이름의 프로그램이 여러 곳에 설치돼 있을 때 지금 실행되는 게 어느 것인지 알려준다.",
    options=[("-a", "<b>a</b>ll", "같은 이름을 모두 표시")],
    examples=[("설치가 됐나 확인", "which node", "아무것도 나오지 않으면 설치가 안 됐거나 PATH에 없는 것이다."),
              ("여러 버전이 섞였을 때", "which -a python3", "/opt/homebrew/bin/python3와 /usr/bin/python3가 둘 다 보이면, 위에 있는 것이 실행된다."),
              ("별명인지 확인", "which ll", "zsh에서는 ll: aliased to ls -lah 처럼 별명도 알려준다.")],
    callouts=[("tip", "\"분명 설치했는데 command not found\"가 뜨면 which로 먼저 확인하자. 설치 위치가 PATH에 빠져 있는 경우가 대부분이다. 해결은 export 항목에 있다.")]),

"sed": dict(
    full="stream editor", syntax="sed 's/찾을말/바꿀말/g' 파일명",
    oneliner="파일 속 글자를 한꺼번에 바꾼다.",
    term=[("cmd", "sed 's/2025/2026/g' notice.txt"), ("out", "2026년 강의 일정 안내"), ("arrow", "결과만 화면에 출력, 원본 파일은 그대로")],
    origin="stream editor. 흘러가는 글자(stream)를 편집한다는 뜻이다. 1970년대 벨 연구소의 리 맥마흔이 ed 편집기의 명령을 파이프 속에서 쓸 수 있게 만든 것이 시작이다.",
    options=[("s", "<b>s</b>ubstitute", "바꾸기 명령 s/찾을말/바꿀말/"),
             ("g", "<b>g</b>lobal", "한 줄에서 모두 바꾸기 (없으면 첫 번째만)"),
             ("-i", "<b>i</b>n-place", "원본 파일을 직접 수정"),
             ("-n + p", "<b>n</b>o print + <b>p</b>rint", "지정한 줄만 출력"),
             ("d", "<b>d</b>elete", "조건에 맞는 줄 삭제")],
    examples=[("파일을 직접 고치기 (macOS)", "sed -i '' 's/http:/https:/g' index.html", "macOS에서는 -i 뒤에 빈 따옴표 ''가 꼭 필요하다. 리눅스와 다른 점이라 자주 막힌다."),
              ("백업을 남기며 고치기", "sed -i .bak 's/foo/bar/g' config.txt", "config.txt.bak에 원본이 남는다."),
              ("주석 줄 지우기", "sed '/^#/d' config.txt", "#으로 시작하는 줄을 빼고 출력한다."),
              ("10~20번째 줄만 보기", "sed -n '10,20p' app.log", "긴 로그에서 원하는 구간만 잘라 본다."),
              ("여러 파일 한 번에", "sed -i '' 's/2025/2026/g' *.md", "모든 .md 파일의 연도를 한꺼번에 고친다.")],
    callouts=[("story", "s/틀린말/맞는말/ 문법은 개발자들의 말버릇이 되었다. 채팅에서 오타를 내면 다음 메시지로 \"s/회으/회의/\"라고만 보내 정정하는 문화가 있을 정도다. 두 글자로 말하는 사람들다운 농담이다."),
              ("tip", "처음에는 -i 없이 실행해 결과를 눈으로 확인하고, 괜찮으면 그때 -i를 붙이자.")]),

"xargs": dict(
    full="extended arguments", syntax="명령1 | xargs 명령2",
    oneliner="앞 명령의 결과를 뒤 명령의 재료로 바꿔준다.",
    term=[("cmd", 'find . -name "*.tmp" | xargs rm'), ("arrow", "찾아낸 .tmp 파일을 rm에 한꺼번에 넘겨 삭제")],
    origin="extended arguments(늘려 주는 인자)로 풀이한다. 파이프(|)가 넘겨주는 글자 뭉치를 잘라서, 뒤 명령의 인자(명령 뒤에 붙는 재료)로 바꿔 붙여 준다.",
    options=[("-I {}", "<b>I</b>nsert (replace)", "{} 자리에 하나씩 끼워 넣기"),
             ("-n", "max <b>n</b>umber", "한 번에 넘길 개수"),
             ("-0", "null (<b>0</b>)", "이름에 공백이 있어도 안전하게 (find -print0과 짝)"),
             ("-p", "<b>p</b>rompt", "실행 전마다 물어보기")],
    examples=[("공백 있는 파일도 안전하게", 'find . -name "*.log" -print0 | xargs -0 rm', "\"my file.log\" 같은 이름도 한 덩어리로 처리된다."),
              ("하나씩 확인하며", "ls *.jpg | xargs -p rm", "지우기 전에 매번 ?...라고 묻는다."),
              ("목록의 주소를 전부 다운로드", "cat urls.txt | xargs -I {} curl -O {}", "{} 자리에 주소가 하나씩 들어가 차례로 실행된다."),
              ("파일마다 줄 수", "ls *.md | xargs wc -l", "파일별 줄 수와 합계가 함께 나온다.")],
    callouts=[("mnemonic", "파이프(|)는 \"내용\"을 넘기고, xargs는 그 내용을 \"명령 뒤에 붙는 재료\"로 바꾼다. rm처럼 입력을 읽지 않고 이름만 받는 명령에 결과를 넘길 때 필요하다.")]),

"chown": dict(
    full="change owner", syntax="chown 사용자[:그룹] 파일명",
    oneliner="파일의 주인을 바꾼다.",
    term=[("cmd", "sudo chown me:staff data.txt"), ("cmd", "ls -l data.txt"),
          ("out", "-rw-r--r--  1 me  staff  812 ... data.txt")],
    origin="change owner. chmod가 \"무엇을 할 수 있나\"를 정한다면, chown은 \"누구의 것인가\"를 정한다. 남의 파일 주인을 바꾸는 일이라 대부분 sudo와 함께 쓴다.",
    options=[("-R", "<b>R</b>ecursive", "폴더 안쪽 전체의 주인 변경"),
             ("-v", "<b>v</b>erbose", "바뀐 파일 표시"),
             ("-h", "symlink (관례상 h)", "링크가 가리키는 곳 말고 링크 자체를")],
    examples=[("root 것이 된 파일 되찾기", "sudo chown $(whoami) report.txt", "$(whoami)는 내 사용자 이름으로 바뀐다."),
              ("npm 권한 오류 해결", "sudo chown -R $(whoami) ~/.npm", "sudo npm으로 설치하다 꼬인 캐시 폴더의 주인을 나로 되돌린다."),
              ("그룹까지 함께", "sudo chown me:staff shared.txt", "콜론(:) 뒤가 그룹이다.")],
    callouts=[("mnemonic", "chmod는 mode(권한), chown은 owner(주인). 둘 다 change로 시작하는 형제 명령이다."),
              ("tip", "sudo로 만든 파일은 주인이 root가 되어 나중에 평범하게 수정할 수 없다. \"Permission denied\"가 뜨면 ls -l로 주인부터 확인하자.")]),

"sudo": dict(
    full="superuser do", syntax="sudo 명령어",
    oneliner="이 명령 하나만 관리자 권한으로 실행한다.",
    term=[("cmd", "sudo softwareupdate -l"), ("out", "Password:"), ("arrow", "맥 로그인 비밀번호 입력 (화면에 안 보이는 게 정상)")],
    origin="superuser do, \"관리자로서 실행하라\". 1980년 뉴욕주립대 버펄로에서 처음 만들어졌다. 관리자 계정으로 아예 로그인하지 않고 필요한 순간에만 권한을 빌리게 해 사고를 줄이는 것이 목적이다.",
    options=[("-i", "<b>i</b>nteractive login", "관리자 셸로 들어가기 (# 프롬프트)"),
             ("-k", "<b>k</b>ill timestamp", "다음번에 비밀번호 다시 묻게"),
             ("-u", "<b>u</b>ser", "다른 사용자로 실행")],
    examples=[("방금 명령을 관리자로 다시", "sudo !!", "!!는 직전 명령. Permission denied가 떴을 때 처음부터 다시 칠 필요가 없다."),
              ("시스템 파일 수정", "sudo nano /etc/hosts", "특정 사이트 주소를 직접 지정할 때 쓰는 파일이다."),
              ("DNS 캐시 비우기 (macOS)", "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder", "사이트 주소가 바뀌었는데 예전 곳으로 접속될 때 쓴다."),
              ("권한 빌린 상태 끝내기", "sudo -k", "잠시 동안 비밀번호를 다시 묻지 않는 상태를 바로 끝낸다.")],
    callouts=[("story", "유명한 웹툰 xkcd에는 \"샌드위치 만들어 줘\"라는 말에 \"네가 만들어\"라고 거절당하던 사람이 \"sudo 샌드위치 만들어 줘\"라고 하자 \"알겠어\"라는 답을 듣는 장면이 있다. 이후 sudo는 개발자들 사이에서 \"꼭 좀\"이라는 뜻의 농담으로도 쓰인다."),
              ("tip", "인터넷에서 복사한 sudo 명령은 컴퓨터 전체를 바꿀 수 있다. 붙여넣기 전에 무슨 뜻인지 반드시 확인하자.")]),

"zip": dict(
    full="zip (지퍼) · unzip", syntax="zip -r 이름.zip 대상 / unzip 이름.zip",
    oneliner="윈도우와도 호환되는 zip 파일로 묶고 푼다.",
    term=[("cmd", "zip -r photos.zip photos/"), ("out", "  adding: photos/a.jpg (deflated 3%)"),
          ("cmd", "unzip photos.zip -d restore/"), ("arrow", "restore 폴더에 압축 해제")],
    origin="지퍼(zip)처럼 빠르게 잠근다는 뜻. 1989년 필 카츠가 만든 PKZIP에서 시작된 형식으로, 지금은 운영체제를 가리지 않는 가장 흔한 압축 형식이 되었다.",
    options=[("-r", "<b>r</b>ecursive", "폴더째 압축"),
             ("-e", "<b>e</b>ncrypt", "비밀번호 걸기"),
             ("-x", "e<b>x</b>clude", "특정 파일 제외"),
             ("-q", "<b>q</b>uiet", "진행 표시 숨기기"),
             ("unzip -l", "<b>l</b>ist", "풀지 않고 목록만"),
             ("unzip -d", "<b>d</b>irectory", "지정한 폴더에 풀기")],
    examples=[("비밀번호 걸어 보내기", "zip -er secret.zip contracts/", "두 번 입력한 비밀번호가 있어야 열 수 있다."),
              ("맥 찌꺼기 빼고 압축", 'zip -r site.zip site -x "*.DS_Store"', "윈도우 사용자에게 보낼 때 깔끔하다."),
              ("열기 전에 내용 확인", "unzip -l archive.zip", "어떤 파일이 들었는지 목록만 본다.")],
    callouts=[("tip", "Finder의 \"압축하기\"로 만든 zip에는 __MACOSX라는 숨은 폴더가 섞여 윈도우 사용자가 당황하곤 한다. 터미널의 zip을 쓰면 이 문제가 없다."),
              ("mnemonic", "맥·리눅스끼리는 tar.gz, 윈도우 사용자에게 보낼 때는 zip. 받는 사람을 먼저 생각하면 고르기 쉽다.")]),

"ping": dict(
    full="ping (소나의 핑 소리)", syntax="ping 주소",
    oneliner="상대 컴퓨터에 신호를 보내 응답을 확인한다.",
    term=[("cmd", "ping -c 3 google.com"), ("out", "64 bytes from 142.250.206.46: icmp_seq=0 ttl=117 time=31.2 ms"),
          ("out", "3 packets transmitted, 3 packets received, 0.0% packet loss")],
    origin="잠수함 소나가 음파를 쏘고 되돌아오는 \"핑\" 소리에서 이름을 땄다. 1983년 마이크 무스가 하룻밤 사이에 만들었다. 흔히 Packet InterNet Groper의 약자로 소개되지만, 이는 나중에 끼워 맞춘 풀이다.",
    options=[("-c", "<b>c</b>ount", "몇 번 보낼지 (없으면 무한)"),
             ("-i", "<b>i</b>nterval", "보내는 간격(초)"),
             ("-t", "<b>t</b>imeout", "몇 초 뒤에 끝낼지")],
    examples=[("인터넷이 되나", "ping -c 3 8.8.8.8", "응답이 오면 인터넷 연결 자체는 살아 있다."),
              ("인터넷 문제인가 주소 문제인가", "ping -c 3 google.com", "8.8.8.8은 되는데 이게 안 되면 주소를 찾아주는 DNS 문제다."),
              ("공유기까지는 되나", "ping 192.168.0.1", "집 안 연결부터 점검한다. Control+C로 멈추면 통계가 나온다.")],
    callouts=[("story", "time=31.2 ms는 신호가 갔다가 돌아오는 데 걸린 시간이다. 게이머들이 말하는 \"핑이 튄다\"의 핑이 바로 이 숫자다.")]),

"top": dict(
    full="top (맨 위)", syntax="top [-o 정렬기준]",
    oneliner="자원을 가장 많이 쓰는 프로그램을 실시간으로 보여준다.",
    term=[("cmd", "top -o cpu"), ("out", "PID    COMMAND      %CPU  MEM"), ("out", "4821   node         87.3  412M"),
          ("out", "612    WindowServer 12.1  256M"), ("arrow", "계속 갱신, q로 종료")],
    origin="자원을 가장 많이 쓰는, 순위의 맨 위(top) 프로그램들을 보여준다는 뜻. 1984년 윌리엄 르페브르가 만들었다. macOS의 활동 모니터 앱과 같은 정보를 터미널에서 본다.",
    options=[("-o", "<b>o</b>rder", "정렬 기준 (cpu, mem 등)"),
             ("-n", "<b>n</b>umber", "보여줄 프로세스 개수"),
             ("-l", "<b>l</b>ogging samples", "몇 번만 찍고 끝낼지 (macOS)"),
             ("q", "<b>q</b>uit", "화면에서 나가기")],
    examples=[("메모리 먹는 순서", "top -o mem", "메모리가 부족하다는 경고가 뜰 때 범인을 찾는다."),
              ("상위 10개만", "top -o cpu -n 10", "화면이 복잡할 때 10개만 본다."),
              ("한 번만 찍고 끝", "top -l 1 | head -12", "실시간 화면 대신 결과를 한 번만 받아 다른 명령에 넘긴다.")],
    callouts=[("tip", "더 보기 좋은 버전으로 htop이 있다. brew install htop으로 설치하면 색깔과 막대그래프로 보여준다.")]),

"lsof": dict(
    full="list open files", syntax="lsof [옵션]",
    oneliner="어떤 프로그램이 무엇을 붙잡고 있는지 보여준다.",
    term=[("cmd", "lsof -i :3000"), ("out", "COMMAND  PID  USER  FD  TYPE  NAME"), ("out", "node    4821  me   23u  IPv6  *:3000 (LISTEN)")],
    origin="list open files, 열려 있는 파일 목록. 유닉스에는 \"모든 것은 파일이다\"라는 철학이 있어서 네트워크 연결까지 파일처럼 다룬다. 그래서 파일 목록 명령으로 포트까지 찾을 수 있다.",
    options=[("-i", "<b>i</b>nternet", "네트워크 연결만 (:포트로 지정)"),
             ("-t", "<b>t</b>erse", "PID 숫자만 출력"),
             ("-p", "<b>p</b>rocess", "특정 PID가 연 파일"),
             ("+D", "<b>D</b>irectory", "특정 폴더 안에서 열린 파일")],
    examples=[("포트를 붙잡은 범인 종료", "kill $(lsof -t -i :3000)", "\"port already in use\" 오류가 날 때 한 줄로 해결한다."),
              ("외장하드가 추출되지 않을 때", "lsof +D /Volumes/USB", "그 디스크의 파일을 열고 있는 프로그램이 나온다. 그 프로그램을 닫으면 추출된다."),
              ("열려 있는 서버 포트 전부", "lsof -i -P | grep LISTEN", "내 맥에서 접속을 기다리는 프로그램 목록이다.")],
    callouts=[("story", "\"모든 것은 파일이다(Everything is a file)\"는 유닉스의 가장 유명한 설계 원칙이다. 키보드, 화면, 네트워크 연결까지 파일처럼 읽고 쓰게 만들어서, 적은 수의 두 글자 명령으로 거의 모든 것을 다룰 수 있게 되었다.")]),

"man": dict(
    full="manual", syntax="man 명령어",
    oneliner="모든 명령어의 공식 설명서를 연다.",
    term=[("cmd", "man ls"), ("out", "LS(1)      General Commands Manual      LS(1)"), ("out", "NAME"), ("out", "     ls – list directory contents"),
          ("arrow", "q로 종료")],
    origin="manual, 설명서. 1971년 켄 톰슨과 데니스 리치가 쓴 첫 유닉스 설명서(Unix Programmer's Manual)의 형식이 지금까지 그대로 이어진다. 설명서는 번호가 붙은 절로 나뉘며, 1절이 우리가 쓰는 명령어다.",
    options=[("-k", "<b>k</b>eyword", "설명에 단어가 들어간 명령 찾기"),
             ("/단어", "search", "설명서 안에서 검색"),
             ("q", "<b>q</b>uit", "설명서 닫기")],
    examples=[("옵션 뜻 찾아보기", "man tar", "화면에서 /-z 처럼 검색하면 그 옵션 설명으로 바로 간다."),
              ("이름을 모르는 명령 찾기", "man -k compress", "압축과 관련된 명령이 설명과 함께 나열된다."),
              ("설명서가 길 때", "man ls | head -30", "앞부분의 NAME과 SYNOPSIS만 봐도 쓰는 법의 절반은 알 수 있다.")],
    callouts=[("tip", "macOS의 명령은 리눅스와 달리 --help를 모르는 경우가 많다. ls --help가 오류를 내면 망설이지 말고 man ls."),
              ("story", "문서에서 ls(1), printf(3)처럼 이름 옆에 붙은 숫자는 man 설명서의 절 번호다. 50년 된 설명서의 흔적이 지금도 개발 문서 곳곳에 남아 있다.")]),

"history": dict(
    full="history (기록)", syntax="history",
    oneliner="지금까지 입력한 명령을 번호와 함께 보여준다.",
    term=[("cmd", "history | tail -3"), ("out", "  512  cd notes"), ("out", "  513  cp draft.md final.md"), ("out", "  514  history | tail -3")],
    origin="이름 그대로 기록. zsh는 입력한 명령을 ~/.zsh_history 파일에 저장해 두었다가 창을 새로 열어도 불러온다.",
    options=[("!!", "last command", "직전 명령 다시 실행"),
             ("!번호", "event number", "그 번호의 명령 다시 실행"),
             ("!문자", "prefix", "그 글자로 시작한 최근 명령"),
             ("Control+R", "<b>r</b>everse search", "입력하는 글자로 과거 명령 검색")],
    options_label="기록을 불러오는 기호와 키",
    examples=[("전체 기록 보기", "history 1", "zsh의 history는 최근 몇 개만 보여준다. 1을 붙이면 처음부터 전부."),
              ("번호로 다시 실행", "!513", "513번 명령(cp draft.md final.md)이 그대로 다시 실행된다."),
              ("과거 명령 검색", "Control + R  →  ssh", "ssh가 들어간 가장 최근 명령이 나타난다. 한 번 더 누르면 그 이전 것."),
              ("특정 명령만 골라 보기", "history 1 | grep git", "git으로 했던 작업만 모아 본다.")],
    callouts=[("tip", "Control+R 역검색은 한 번 익히면 다시는 돌아갈 수 없는 기능이다. 긴 명령을 다시 칠 일이 거의 사라진다.")]),

"pbcopy": dict(
    full="pasteboard copy · pbpaste (macOS 전용)", syntax="명령 | pbcopy  /  pbpaste",
    oneliner="터미널과 클립보드(Cmd+C·Cmd+V)를 잇는다.",
    term=[("cmd", "cat ~/.ssh/id_ed25519.pub | pbcopy"), ("arrow", "공개키가 클립보드에 복사됨, Cmd+V로 붙여넣기"),
          ("cmd", "pbpaste > note.txt"), ("arrow", "클립보드 내용을 파일로 저장")],
    origin="pasteboard copy. macOS는 클립보드를 붙여넣기 판(pasteboard)이라고 부른다. NeXTSTEP 시절부터 쓰던 용어가 명령어 이름에 남았다. 짝인 pbpaste는 반대로 클립보드 내용을 꺼내 온다.",
    options=[("pbcopy", "<b>p</b>aste<b>b</b>oard copy", "입력받은 내용을 클립보드로"),
             ("pbpaste", "<b>p</b>aste<b>b</b>oard paste", "클립보드 내용을 출력")],
    options_label="짝을 이루는 두 명령",
    examples=[("GitHub에 SSH 키 등록", "pbcopy < ~/.ssh/id_ed25519.pub", "마우스로 긁다가 한 글자 빠뜨리는 실수가 없다."),
              ("현재 경로 복사", "pwd | pbcopy", "동료에게 폴더 위치를 알려줄 때."),
              ("복사한 목록 정리해 다시 복사", "pbpaste | sort -u | pbcopy", "웹에서 복사한 목록의 중복을 없애고 정렬해서 다시 클립보드에 넣는다."),
              ("명령 결과 공유", "ls -la | pbcopy", "결과를 그대로 메신저나 이슈에 붙여넣는다.")],
    callouts=[("tip", "pbpaste | 명령 | pbcopy 조합을 기억해 두자. 클립보드에 있는 글을 터미널 명령으로 가공해 다시 클립보드로 돌려보내는, 맥에서만 가능한 요령이다.")]),

"caffeinate": dict(
    full="caffeinate (macOS 전용)", syntax="caffeinate [옵션] [명령]",
    oneliner="맥이 잠들지 않게 커피를 먹인다.",
    term=[("cmd", "caffeinate -t 3600"), ("arrow", "1시간 동안 잠자기 모드로 들어가지 않음")],
    origin="caffeine(카페인)에 동사 어미 -ate를 붙인 애플의 말장난이다. \"맥에게 커피를 먹인다\"는 뜻으로, 2012년 OS X Mountain Lion에 들어왔다.",
    options=[("-d", "<b>d</b>isplay", "화면이 꺼지지 않게"),
             ("-i", "<b>i</b>dle", "시스템이 잠들지 않게"),
             ("-t", "<b>t</b>imeout", "몇 초 동안만"),
             ("-w", "<b>w</b>ait for PID", "그 프로세스가 끝날 때까지")],
    examples=[("긴 다운로드 동안만", "caffeinate -i curl -O https://example.com/big.iso", "다운로드가 끝나면 자동으로 원래대로 돌아간다."),
              ("발표 중 화면 유지", "caffeinate -d", "Control+C를 누를 때까지 화면이 꺼지지 않는다."),
              ("백업 스크립트 끝날 때까지", "caffeinate -i ./backup.sh", "명령 앞에 붙이기만 하면 된다."),
              ("이미 실행 중인 작업을 지키기", "caffeinate -w 4821", "PID 4821 프로그램이 끝날 때까지 깨어 있는다.")],
    callouts=[("story", "애플 엔지니어들의 유머 감각이 드러나는 몇 안 되는 명령어 이름이다. 두 글자로 말하는 사람들 사이에서 거의 유일하게 긴 이름을 당당히 쓰는 명령이기도 하다.")]),

"say": dict(
    full="say (말하다, macOS 전용)", syntax='say "문장"',
    oneliner="맥이 글자를 소리 내어 읽는다.",
    term=[("cmd", 'say -v Yuna "빌드가 끝났습니다"'), ("arrow", "스피커에서 한국어 음성으로 재생")],
    origin="이름 그대로 \"말하다\". 1984년 첫 매킨토시 발표 무대에서 맥이 스스로 \"Hello, I'm Macintosh\"라고 인사했던 음성 합성 기술의 후손이다.",
    options=[("-v", "<b>v</b>oice", "목소리 선택 (Yuna는 한국어)"),
             ("-r", "<b>r</b>ate", "말하는 속도 (분당 단어 수)"),
             ("-o", "<b>o</b>utput file", "소리를 파일로 저장"),
             ("-f", "<b>f</b>ile", "텍스트 파일을 통째로 읽기")],
    examples=[("작업이 끝나면 알려줘", './backup.sh; say "백업이 끝났어요"', ";는 앞 명령이 끝나면 성공과 상관없이 다음 명령을 실행한다. 다른 일을 하다가 소리로 알 수 있다."),
              ("쓸 수 있는 목소리 목록", "say -v '?'", "언어별 목소리와 예문이 나열된다."),
              ("음성 파일 만들기", 'say -v Yuna -o hello.aiff "안녕하세요"', "안내 방송용 음성 파일을 뚝딱 만든다."),
              ("원고 소리 내어 검토", "say -v Yuna -f essay.txt", "눈으로는 놓친 어색한 문장이 귀에는 걸린다.")],
    callouts=[("tip", "긴 빌드나 다운로드 명령 끝에 ; say 완료 를 붙여 두는 습관을 들이면 터미널을 계속 지켜볼 필요가 없다.")]),
}
