# Chapter 13 walkthrough data.
# lines: (prompt, command, [output lines]); output lines starting with "→ " render as explanation arrows
# dissect: (command, [(token, meaning)], result_text)
# outside: [(command, explanation)] for tools not covered in this book

P0 = "~ %"
P1 = "lecture-site %"

STEPS = [
dict(n=1, time="09:00", title="작업할 자리 만들기",
     situation="지민은 앞으로 만들 프로젝트를 한곳에 모아 두기로 했다. 홈 폴더 아래 Projects 폴더를 만들고, 그 안에 이번 강의 사이트용 폴더를 만든 뒤 들어간다.",
     lines=[(P0, "mkdir -p ~/Projects/lecture-site", ["(출력 없음)"]),
            (P0, "cd ~/Projects/lecture-site", ["→ 프롬프트가 lecture-site % 로 바뀜"]),
            (P1, "pwd", ["/Users/jimin/Projects/lecture-site"])],
     dissect=[("mkdir -p ~/Projects/lecture-site",
               [("mkdir", "폴더를 만드는 명령 (make directory)"),
                ("-p", "중간 폴더인 Projects가 아직 없어도 함께 만들라는 옵션"),
                ("~", "내 홈 폴더 /Users/jimin을 줄여 쓴 기호"),
                ("/Projects/lecture-site", "홈 아래 Projects, 그 아래 lecture-site라는 경로")],
               "아무 말도 없으면 성공이다. 유닉스 명령은 잘 되면 조용하고, 문제가 있을 때만 말한다."),
              ("cd ~/Projects/lecture-site",
               [("cd", "다른 폴더로 이동하는 명령 (change directory)"),
                ("~/Projects/lecture-site", "방금 만든 폴더의 경로")],
               "출력은 없지만 프롬프트의 위치 표시가 lecture-site로 바뀐다. 이제부터 모든 명령은 이 폴더 안에서 실행된다."),
              ("pwd",
               [("pwd", "지금 있는 폴더의 전체 경로를 출력 (print working directory)")],
               "프롬프트는 공간을 아끼려고 마지막 폴더 이름만 보여준다. 정확한 위치가 궁금할 때는 pwd로 확인한다.")],
     mistake="mkdir만 하고 cd를 잊으면 이후에 만드는 파일이 모두 홈 폴더에 흩어진다. 새 폴더를 만들면 바로 들어가는 습관을 들이거나, mkdir -p 폴더 && cd 폴더 처럼 한 줄로 이어 쓴다.",
     used=["mkdir", "cd", "pwd"]),

dict(n=2, time="09:05", title="도구가 준비됐는지 확인하기",
     situation="웹사이트를 만들려면 Node.js와 git이 필요하다. 예전에 설치한 기억은 있지만 정말 있는지, 어디에 있는지 확인한다.",
     lines=[(P1, "which node git", ["/opt/homebrew/bin/node", "/usr/bin/git"]),
            (P1, "node -v", ["v22.9.0"])],
     dissect=[("which node git",
               [("which", "명령어가 실제로 어디 있는 프로그램인지 찾는 명령"),
                ("node git", "찾을 이름 두 개. 공백으로 나열하면 한 번에 여러 개를 물을 수 있다")],
               "두 줄이 나왔으니 둘 다 설치돼 있다. /opt/homebrew/bin은 Homebrew로 설치한 프로그램이 모이는 곳이고, /usr/bin은 macOS에 원래 들어 있는 프로그램의 자리다. 아무 줄도 나오지 않는 이름이 있다면 설치되지 않았거나 PATH에 빠져 있는 것이다.")],
     outside=[("node -v", "Node.js의 버전을 확인한다. -v는 version의 약자로, 대부분의 프로그램이 -v나 --version으로 버전을 알려준다. 튜토리얼이 요구하는 버전과 맞는지 비교할 때 쓴다.")],
     mistake="분명히 설치했는데 command not found가 뜬다면 설치 위치가 PATH에 없는 경우가 대부분이다. which -a로 같은 프로그램이 여러 개 있는지 보고, export 항목의 PATH 추가 방법을 따라 한다.",
     used=["which"]),

dict(n=3, time="09:10", title="뼈대 세우기",
     situation="동료가 쓰던 시작 템플릿에서 설정 파일(package.json)을 복사해 오고, 사이트에 필요한 폴더와 빈 파일을 만든다. 마지막으로 제대로 만들어졌는지 눈으로 확인한다.",
     lines=[(P1, "cp ~/Templates/vite-starter/package.json .", ["(출력 없음)"]),
            (P1, "mkdir -p src/{components,assets} docs", ["(출력 없음)"]),
            (P1, "touch README.md .gitignore", ["(출력 없음)"]),
            (P1, "ls -la", ["drwxr-xr-x  7 jimin  staff  224  9 30 09:12 .",
                            "-rw-r--r--  1 jimin  staff    0  9 30 09:12 .gitignore",
                            "-rw-r--r--  1 jimin  staff    0  9 30 09:12 README.md",
                            "drwxr-xr-x  2 jimin  staff   64  9 30 09:12 docs",
                            "-rw-r--r--  1 jimin  staff  612  9 30 09:11 package.json",
                            "drwxr-xr-x  4 jimin  staff  128  9 30 09:12 src"])],
     dissect=[("cp ~/Templates/vite-starter/package.json .",
               [("cp", "파일을 복사하는 명령 (copy)"),
                ("~/Templates/vite-starter/package.json", "복사할 원본 파일의 경로"),
                (".", "지금 있는 폴더. 대상이 폴더이면 원래 이름 그대로 그 안에 복사된다")],
               "조용하면 성공이다. package.json은 이 프로젝트에 어떤 부품이 필요한지 적어 둔 목록이다. 5단계에서 이 목록을 보고 부품을 설치한다."),
              ("mkdir -p src/{components,assets} docs",
               [("-p", "상위 폴더 src가 없어도 함께 만든다"),
                ("src/{components,assets}", "중괄호 확장. 셸이 src/components와 src/assets 두 경로로 펼쳐서 mkdir에 넘겨준다"),
                ("docs", "세 번째로 만들 폴더. 공백으로 구분해 여러 개를 한 번에 적는다")],
               "한 줄로 폴더 네 개(src, src/components, src/assets, docs)가 생긴다."),
              ("touch README.md .gitignore",
               [("touch", "파일이 없으면 빈 파일을 만드는 명령"),
                ("README.md", "프로젝트 설명서. GitHub에 올리면 첫 화면에 보인다"),
                (".gitignore", "git에 올리지 않을 파일 목록. 점(.)으로 시작해서 숨김 파일이 된다")],
               "크기 0바이트짜리 빈 파일 두 개가 생긴다. 내용은 다음 단계에서 채운다."),
              ("ls -la",
               [("ls", "폴더 안의 내용을 나열하는 명령 (list)"),
                ("-l", "long. 권한·주인·크기·날짜까지 한 줄에 하나씩 자세히"),
                ("-a", "all. 이름이 점으로 시작하는 숨김 파일까지 모두")],
               "맨 앞 글자가 d면 폴더, -면 파일이다. 크기 칸의 0은 방금 만든 빈 파일, 612는 복사해 온 package.json의 크기(바이트)다. .gitignore가 보이는 건 -a 덕분이다. -a를 빼면 목록에서 사라진다.")],
     mistake="{components, assets}처럼 쉼표 뒤에 공백을 넣으면 중괄호 확장이 깨져서 '{components,'와 'assets}'라는 엉뚱한 폴더가 생긴다. 중괄호 안에는 공백을 넣지 않는다.",
     used=["cp", "mkdir", "touch", "ls"]),

dict(n=4, time="09:20", title="설정 파일 채우기",
     situation="git에 올리면 안 되는 것들을 .gitignore에 적는다. 수백 MB짜리 부품 폴더(node_modules)와 비밀번호를 담을 파일(.env)이다. 편집기를 열지 않고 터미널에서 바로 쓴다.",
     lines=[(P1, 'echo "node_modules" >> .gitignore', ["(출력 없음)"]),
            (P1, 'echo ".env" >> .gitignore', ["(출력 없음)"]),
            (P1, "cat .gitignore", ["node_modules", ".env"])],
     dissect=[('echo "node_modules" >> .gitignore',
               [("echo", "따옴표 안의 글자를 그대로 내보내는 명령"),
                ('"node_modules"', "내보낼 글자. 설치한 부품이 모이는 폴더의 이름"),
                (">>", "결과를 화면 대신 파일 맨 끝에 덧붙이라는 기호"),
                (".gitignore", "글자를 덧붙일 파일")],
               "화면에 아무것도 나오지 않는다. 화면에 나올 글자가 파일 속으로 들어갔기 때문이다."),
              ('echo ".env" >> .gitignore',
               [('".env"', "API 키나 비밀번호를 적어 두는 파일의 이름. 절대 인터넷에 올리면 안 된다")],
               "첫 줄 아래에 두 번째 줄이 덧붙는다."),
              ("cat .gitignore",
               [("cat", "파일 내용을 화면에 그대로 보여주는 명령 (concatenate)"),
                (".gitignore", "내용을 볼 파일")],
               "두 줄이 적은 순서대로 들어 있다. 편집기를 열지 않고도 파일 내용을 확인할 수 있다.")],
     mistake=">> 대신 >를 쓰면 파일을 매번 새로 덮어써서 마지막 한 줄만 남는다. 두 번째 echo에서 >를 쓰면 node_modules 줄이 사라져, 나중에 수백 MB가 통째로 git에 올라가는 사고가 난다.",
     used=["echo", "cat"]),

dict(n=5, time="09:30", title="개발 서버 켜기, 그리고 첫 번째 막힘",
     situation="부품을 설치하고 개발 서버를 켜려는데 오류가 난다. 어제 켜 두고 잊어버린 서버가 아직 같은 포트(문 번호)를 붙잡고 있었다. 범인을 찾아 끄고 다시 켠다.",
     lines=[(P1, "npm install", ["added 212 packages in 9s"]),
            (P1, "npm run dev", ["Error: Port 5173 is already in use"]),
            (P1, "lsof -i :5173", ["COMMAND  PID   USER   FD   TYPE  NAME",
                                   "node    4821  jimin  23u  IPv6  *:5173 (LISTEN)"]),
            (P1, "kill 4821", ["(출력 없음)"]),
            (P1, "npm run dev", ["  Local:   http://localhost:5173/"])],
     dissect=[("lsof -i :5173",
               [("lsof", "어떤 프로그램이 무엇을 열고 있는지 보여주는 명령 (list open files)"),
                ("-i", "그중 네트워크 연결만 보라는 옵션 (internet)"),
                (":5173", "5173번 포트만. 콜론 뒤에 포트 번호를 적는다")],
               "COMMAND 칸의 node가 프로그램 이름, PID 칸의 4821이 그 프로그램의 고유 번호다. 맨 끝의 LISTEN은 \"손님을 기다리는 중\"이라는 뜻이다. 어제 끄지 않은 개발 서버가 아직 문을 열고 있었다."),
              ("kill 4821",
               [("kill", "프로그램에 신호를 보내는 명령. 숫자 없이 쓰면 \"정리하고 끝내 주세요\"라는 정상 종료 요청"),
                ("4821", "신호를 받을 프로그램의 PID. 바로 앞 lsof에서 알아낸 번호")],
               "조용하면 성공이다. 그래도 꺼지지 않으면 강제 종료인 kill -9 4821을 쓴다.")],
     outside=[("npm install", "package.json에 적힌 부품(패키지)을 인터넷에서 받아 node_modules 폴더에 설치한다. \"212개를 9초 만에 설치했다\"는 결과다."),
              ("npm run dev", "개발용 서버를 켠다. 코드를 고치면 브라우저에 바로 반영된다. 마지막 줄의 주소를 브라우저에 넣으면 사이트가 보인다.")],
     mistake="포트 오류를 보고 맥을 재부팅하는 사람이 많다. 두 줄이면 끝나는 일이다. 익숙해지면 kill $(lsof -t -i :5173) 한 줄로 줄일 수 있다.",
     used=["lsof", "kill"]),

dict(n=6, time="11:00", title="작업하면서 수시로",
     situation="오전 내내 슬라이드 페이지를 만들었다. 중간중간 남은 할 일을 찾고, 만든 파일 수를 세고, 작년 자료에서 가져온 문서의 연도를 한꺼번에 고친다.",
     lines=[(P1, 'grep -rn "TODO" src/', ["src/App.tsx:42:// TODO: 3장 슬라이드 추가", "src/Slide.tsx:17:// TODO: 이미지 크기 조정"]),
            (P1, 'find src -name "*.tsx" | wc -l', ["      14"]),
            (P1, "sed -i '' 's/2025/2026/g' docs/*.md", ["(출력 없음)"]),
            (P1, 'grep -rn "2025" docs/', ["(출력 없음)"])],
     dissect=[('grep -rn "TODO" src/',
               [("grep", "파일 속에서 글자를 찾는 명령"),
                ("-r", "지정한 폴더와 그 아래 모든 파일에서 찾는다 (recursive)"),
                ("-n", "찾은 줄이 몇 번째 줄인지 번호를 붙인다 (line number)"),
                ('"TODO"', "찾을 글자. 개발자들이 \"나중에 할 일\"을 표시할 때 쓰는 관례적인 단어"),
                ("src/", "찾을 범위")],
               "결과는 \"파일 이름:줄 번호:그 줄의 내용\" 형식이다. 남은 할 일이 두 개이고, 편집기에서 App.tsx의 42번째 줄로 바로 가면 된다."),
              ('find src -name "*.tsx" | wc -l',
               [("find src", "src 폴더 안을 뒤진다"),
                ('-name "*.tsx"', "이름이 .tsx로 끝나는 파일만. *는 '아무 글자나'"),
                ("|", "파이프. 앞 명령의 결과를 뒤 명령에 넘긴다"),
                ("wc -l", "넘겨받은 결과의 줄 수를 센다. 파일이 한 줄에 하나씩이므로 곧 파일 개수")],
               "화면 부품(.tsx) 파일이 14개라는 뜻이다. 두 명령을 파이프로 이으면 \"찾아서 세기\"라는 새 기능이 생긴다."),
              ("sed -i '' 's/2025/2026/g' docs/*.md",
               [("sed", "흘러가는 글자를 편집하는 명령 (stream editor)"),
                ("-i ''", "결과를 화면에 보이는 대신 원본 파일을 직접 고친다. macOS에서는 뒤에 빈 따옴표가 꼭 필요하다"),
                ("'s/2025/2026/g'", "바꾸기 규칙. s는 substitute(바꾸기), 2025를 2026으로, g는 한 줄에 여러 개 있어도 모두"),
                ("docs/*.md", "docs 폴더의 모든 .md 파일")],
               "조용하면 성공이다. 문서가 몇 개든 한 번에 고쳐진다."),
              ('grep -rn "2025" docs/',
               [('"2025"', "남아 있는 옛 연도가 있는지 다시 찾는다")],
               "아무것도 나오지 않으면 모두 바뀌었다는 뜻이다. 고친 뒤 grep으로 확인하는 것까지가 한 세트다.")],
     mistake="sed -i를 처음부터 쓰면 되돌릴 수 없다. 먼저 -i 없이 실행해 화면으로 결과를 확인하거나, -i .bak을 써서 원본을 .bak 파일로 남겨 둔다.",
     used=["grep", "find", "wc", "sed"]),

dict(n=7, time="15:00", title="올리기 전 점검",
     situation="오후에 첫 버전이 완성됐다. 인터넷에 올리기 전에 세 가지를 점검한다. 비밀키가 코드에 섞이지 않았는지, 맥이 몰래 만든 찌꺼기 파일은 없는지, 어떤 폴더가 무거운지.",
     lines=[(P1, 'grep -rl "API_KEY" . --exclude-dir=node_modules', ["./.env"]),
            (P1, 'find . -name ".DS_Store" -delete', ["(출력 없음)"]),
            (P1, "du -sh * | sort -rh", ["187M    node_modules", "1.2M    src", " 24K    docs", "4.0K    package.json", "  0B    README.md"])],
     dissect=[('grep -rl "API_KEY" . --exclude-dir=node_modules',
               [("-r", "모든 하위 폴더까지"),
                ("-l", "내용은 빼고 그 글자가 든 파일 이름만 (list files)"),
                ('"API_KEY"', "비밀키 변수에 흔히 붙이는 이름"),
                (".", "현재 폴더 전체"),
                ("--exclude-dir=node_modules", "설치한 부품 폴더는 건너뛴다. 파일이 수만 개라 느리고, 내가 쓴 코드도 아니다")],
               ".env 한 곳에서만 나왔다. .env는 4단계에서 .gitignore에 넣었으니 올라가지 않는다. 만약 src 안의 파일 이름이 나왔다면 코드에 비밀키가 직접 적힌 것이니 반드시 고쳐야 한다."),
              ('find . -name ".DS_Store" -delete',
               [("find .", "현재 폴더 전체를 뒤진다"),
                ('-name ".DS_Store"', "Finder가 폴더마다 몰래 만드는 설정 파일의 이름"),
                ("-delete", "찾자마자 지운다")],
               "조용하면 끝이다. 이 파일은 다른 사람에게 쓸모가 없고 폴더 구조를 노출하기도 해서 올리기 전에 지우는 것이 좋다."),
              ("du -sh * | sort -rh",
               [("du", "용량을 재는 명령 (disk usage)"),
                ("-s", "하위 폴더를 나열하지 않고 항목마다 합계 한 줄씩"),
                ("-h", "K, M, G 같은 읽기 쉬운 단위로"),
                ("*", "현재 폴더의 모든 항목"),
                ("sort -rh", "단위를 이해하면서(-h) 큰 것부터(-r) 정렬")],
               "node_modules가 187M로 압도적으로 크고, 지민이 직접 쓴 코드(src)는 1.2M뿐이다. 그래서 node_modules를 .gitignore에 넣어 올리지 않는 것이다.")],
     mistake="grep 결과가 비어 있다고 안심하기 전에 검색어를 한 번 더 생각하자. 서비스마다 SECRET, TOKEN, PASSWORD처럼 다른 이름을 쓴다. grep -rlE \"API_KEY|SECRET|TOKEN\"처럼 여러 단어를 한 번에 찾으면 더 안전하다.",
     used=["grep", "find", "du", "sort"]),

dict(n=8, time="16:00", title="저장하고 내보내기",
     situation="작업 기록을 남기고, 배포용 파일을 만들어 서버에 올린다. 올리기 전에 서버에 자리가 충분한지 확인하고, 마지막으로 날짜가 붙은 백업을 만든다.",
     lines=[(P1, 'git init && git add . && git commit -m "First lecture site"', ["[main (root-commit) a1b2c3d] First lecture site", " 9 files changed, 214 insertions(+)"]),
            (P1, "npm run build", ["built in 1.84s"]),
            (P1, 'ssh jimin@myserver "df -h /var/www"', ["Filesystem  Size  Used  Avail  Use%  Mounted on", "/dev/sda1    40G   12G    28G   30%  /"]),
            (P1, "rsync -avz dist/ jimin@myserver:/var/www/lecture/", ["sending incremental file list", "index.html", "assets/index-4f2a.js", "sent 1,204,881 bytes  received 412 bytes"]),
            (P1, "tar -czf ~/Backups/lecture-$(date +%Y%m%d).tar.gz --exclude=node_modules .", ["(출력 없음)"])],
     dissect=[('ssh jimin@myserver "df -h /var/www"',
               [("ssh", "다른 컴퓨터에 암호화된 연결로 접속하는 명령 (secure shell)"),
                ("jimin@myserver", "서버의 사용자 이름@서버 주소"),
                ('"df -h /var/www"', "접속해서 실행할 명령. 따옴표 안의 명령만 실행하고 바로 내 맥으로 돌아온다"),
                ("df -h", "디스크의 남은 공간을 읽기 쉬운 단위로 보여준다 (disk free)")],
               "서버 디스크 40G 중 28G가 남아 있다(Avail). 1.2MB짜리 사이트를 올리기에 충분하다. 서버에 들어가 살펴보고 나오는 과정을 한 줄로 줄였다."),
              ("rsync -avz dist/ jimin@myserver:/var/www/lecture/",
               [("rsync", "바뀐 부분만 골라 복사하는 동기화 명령 (remote sync)"),
                ("-a", "권한·날짜까지 원본 그대로 (archive)"),
                ("-v", "보내는 파일 목록을 보여준다 (verbose)"),
                ("-z", "압축해서 보내 전송 시간을 줄인다 (zip)"),
                ("dist/", "보낼 폴더. 끝의 /는 \"폴더 안의 내용물\"이라는 뜻"),
                ("jimin@myserver:/var/www/lecture/", "받는 곳. 콜론 뒤가 서버 안의 경로")],
               "보낸 파일 목록과 전송량(약 1.2MB)이 나온다. 다음에 다시 배포하면 바뀐 파일만 전송되어 훨씬 빨리 끝난다."),
              ("tar -czf ~/Backups/lecture-$(date +%Y%m%d).tar.gz --exclude=node_modules .",
               [("tar", "여러 파일을 하나로 묶는 명령 (tape archive)"),
                ("-c", "새 압축 파일을 만든다 (create)"),
                ("-z", "gzip으로 압축한다"),
                ("-f", "바로 뒤에 압축 파일 이름이 온다 (file)"),
                ("$(date +%Y%m%d)", "date 명령의 결과, 즉 오늘 날짜 20260930이 이 자리에 들어간다"),
                ("--exclude=node_modules", "다시 설치할 수 있는 부품 폴더는 뺀다"),
                (".", "묶을 대상. 현재 폴더 전체")],
               "~/Backups/lecture-20260930.tar.gz 파일이 생긴다. 날짜가 이름에 들어가 있어서 백업이 쌓여도 헷갈리지 않는다.")],
     outside=[('git init && git add . && git commit -m "…"', "git은 작업 기록을 저장하는 도구다. init은 기록을 시작하고, add .은 모든 파일을 기록 대상에 올리고, commit은 메시지와 함께 지금 상태를 저장한다. &&는 앞 명령이 성공했을 때만 다음 명령을 실행한다."),
              ("npm run build", "사이트를 배포용으로 가볍게 만들어 dist 폴더에 담는다. 서버에 올리는 것은 이 dist 폴더다.")],
     mistake="rsync에서 dist/ 대신 dist라고 쓰면 서버에 폴더가 한 겹 더 생겨 /var/www/lecture/dist가 된다. 사이트 주소가 바뀌어 버린다. 끝의 슬래시 하나가 결과를 바꾼다. 불안하면 -n을 붙여 예행연습부터 한다.",
     used=["ssh", "df", "rsync", "tar"]),

dict(n=9, time="18:00", title="내일을 위한 정리",
     situation="하루를 마무리하며 내일 더 빨리 시작할 수 있게 준비한다. 긴 폴더 경로에 별명을 붙이고, Finder로 결과물을 한 번 훑어본 뒤, 맥에게 퇴근을 알리게 한다.",
     lines=[(P1, "echo \"alias lec='cd ~/Projects/lecture-site'\" >> ~/.zshrc", ["(출력 없음)"]),
            (P1, "source ~/.zshrc", ["(출력 없음)"]),
            (P0, "lec", ["→ 어디에 있든 lecture-site 폴더로 이동"]),
            (P1, "open .", ["→ Finder 창에 lecture-site 폴더가 열림"]),
            (P1, 'say -v Yuna "오늘 작업 끝"', ["→ 스피커에서 \"오늘 작업 끝\""])],
     dissect=[("echo \"alias lec='cd ~/Projects/lecture-site'\" >> ~/.zshrc",
               [("alias lec='…'", "lec라는 짧은 별명이 따옴표 안의 명령을 대신하게 한다"),
                ("큰따옴표 속 작은따옴표", "alias 정의에도 따옴표가 필요해서, 바깥은 큰따옴표로 안은 작은따옴표로 겹쳐 쓴다"),
                (">> ~/.zshrc", "터미널이 켜질 때마다 읽는 설정 파일의 맨 끝에 덧붙인다")],
               "조용하면 설정 파일에 한 줄이 추가된 것이다. 하지만 이미 열려 있는 이 창은 아직 모른다."),
              ("source ~/.zshrc",
               [("source", "파일을 지금 이 창에서 다시 읽어 즉시 적용하는 명령"),
                ("~/.zshrc", "방금 한 줄을 추가한 설정 파일")],
               "이제 이 창에서도 lec가 통한다. 새 창을 열 필요가 없다."),
              ("open .",
               [("open", "Finder에서 더블클릭한 것처럼 여는 macOS 전용 명령"),
                (".", "지금 폴더")],
               "터미널에서 작업한 결과를 Finder 창으로 눈으로 확인한다."),
              ('say -v Yuna "오늘 작업 끝"',
               [("say", "글자를 소리 내어 읽는 macOS 전용 명령"),
                ("-v Yuna", "한국어 목소리 Yuna를 고른다 (voice)"),
                ('"오늘 작업 끝"', "읽을 문장")],
               "맥이 한국어로 하루의 끝을 알려준다. 긴 작업 끝에 붙여 두면 알림으로도 쓸 수 있다.")],
     mistake="source를 잊고 lec를 치면 command not found가 뜬다. 설정 파일을 고쳤다면 source를 실행하거나 새 창을 연다.",
     used=["echo", "alias", "source", "open", "say"]),
]
